Useful Links:

https://problemsolvingwithpython.com/04-Data-Types-and-Variables/04.05-Dictionaries-and-Tuples/

https://www.w3schools.com/python/

https://www.javatpoint.com/python-tutorial

https://www.geeksforgeeks.org/python-gui-tkinter/

https://www.javatpoint.com/python-tkinter

**What is Python?**
Python is a popular programming language. It was created by Guido van Rossum, and released in 1991.

It is used for:

web development (server-side),
software development,
mathematics,
system scripting.

**What can Python do?**
*   Python can be used on a server to create web applications.
*   Python can be used alongside software to create workflows.
*   Python can connect to database systems. It can also read and modify files.
*   Python can be used to handle big data and perform complex mathematics.
*   Python can be used for rapid prototyping, or for production-ready software development.


**Why Python?**

*   Python works on different platforms (Windows, Mac, Linux, Raspberry Pi, etc).
*   Python has a simple syntax similar to the English language.
*   Python has syntax that allows developers to write programs with fewer lines than some other programming languages.
*   Python runs on an interpreter system, meaning that code can be executed as soon as it is written. This means that prototyping can be very quick.
*   Python can be treated in a procedural way, an object-oriented way or a functional way.


**Python Syntax compared to other programming languages**

Python was designed for readability, and has some similarities to the English

*   language with influence from mathematics.
*   Python uses new lines to complete a command, as opposed to other
*   programming languages which often use semicolons or parentheses.
*   Python relies on indentation, using whitespace, to define scope; such as the scope of loops, functions and classes.
*   Other programming languages often use curly-brackets for this purpose.

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

**Python Syntax**

In [ ]:
print("Hello, World!")

Hello, World!

**Python Indentation**

Indentation refers to the spaces at the beginning of a code line.

Where in other programming languages the indentation in code is for readability only, the indentation in Python is very important.

Python uses indentation to indicate a block of code.

<font color='red'>**Note: Python will give you an error if you skip the indentation:**</font>

In [ ]:
if 5 > 2:
  print("Five is greater than two!")
  print("Two is smaller than 5!")

Five is greater than two!
Two is smaller than 5!


# Comments

Python has commenting capability for the purpose of in-code documentation.

Comments start with a #, and Python will render the rest of the line as a comment:

Comments can be placed at the end of a line, and Python will ignore the rest of the line:

For multiline comment you can add a multiline string (triple quotes) in your code, and place your comment inside it:

In [ ]:

#This is a comment.
print("Hello, World!")
print("# for single line comment") #This is a comment
"""
This is a comment
written in
more than just one line
"""
print("Hello, World!")

Hello, World!
# for single line comment
Hello, World!

# Python Variables
In Python, variables are created when you assign a value to it:

Python has no command for declaring a variable

In [ ]:
x = 5
y = "John"
print(x)
print(y)

5
John

#Casting
If you want to specify the data type of a variable, this can be done with casting.
#Example

In [ ]:
x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0

#Get the Type
You can get the data type of a variable with the type() function.

In [ ]:
x = 5
y = "John"
print(type(x))
print(type(y))

<class 'int'>
<class 'str'>

#Single or Double Quotes?
String variables can be declared either by using single or double quotes:

In [ ]:
x = "John"
print(x)
# is the same as
x = 'John'
print(x)

John
John

#Case-Sensitive
Variable names are case-sensitive.

In [ ]:
a = 4
A = "Sally"
#A will not overwrite a

#Variable Names
* A variable can have a short name (like x and y) or a more descriptive name (age, carname, total_volume). Rules for Python variables:
* A variable name must start with a letter or the underscore character
* A variable name cannot start with a number
* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
* Variable names are case-sensitive (age, Age and AGE are three different variables)
* A variable name cannot be any of the Python keywords.
#Example

In [ ]:
myvar = "John"
my_var = "John"
_my_var = "John"
myVar = "John"
MYVAR = "John"
myvar2 = "John123"
print(type(myvar2))

<class 'str'>

##Python Variables - Assign Multiple Values
#Many Values to Multiple Variables
Python allows you to assign values to multiple variables in one line:

Example

In [ ]:
x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)

Orange
Banana
Cherry

#One Value to Multiple Variables
And you can assign the same value to multiple variables in one line:

In [ ]:
x = y = z = "Orange"
print(x)
print(y)
print(z)

Orange
Orange
Orange

#Unpack a Collection
If you have a collection of values in a list, tuple etc. Python allows you to extract the values into variables. This is called unpacking.

In [ ]:
fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(z)

#Output Variables
The Python print() function is often used to output variables.

In the print() function, you output multiple variables, separated by a comma:

You can also use the + operator to output multiple variables:

For numbers, the + character works as a mathematical operator:

In the print() function, when you try to combine a string and a number with the + operator, Python will give you an error:

The best way to output multiple variables in the print() function is to separate them with commas, which even support different data types:

In [ ]:
x = "Python is awesome"
print(x)

x = "Python"
y = "is"
z = "awesome"
print(x,y,z)

x = "Python "
y = "is "
z = "awesome"
print(x + y + z)

x = 5
y = 10
print(x + y)

x = 5
y = "John"
#print(x + y) #TypeError: unsupported operand type(s) for +: 'int' and 'str'

x = 5
y = "John"
print(x, y)

Python is awesome
Python is awesome
Python is awesome
15
5 John

#Global Variables
Variables that are created outside of a function (as in all of the examples above) are known as global variables.

Global variables can be used by everyone, both inside of functions and outside.

ExampleGet your own Python Server
Create a variable outside of a function, and use it inside the function

In [ ]:
def assign():
  global x
  x="awesome"

def myfunc():
  print("Python is " + x)

myfunc()

Python is awesome

If you create a variable with the same name inside a function, this variable will be local, and can only be used inside the function. The global variable with the same name will remain as it was, global and with the original value.

#Example
Create a variable inside a function, with the same name as the global variable

In [ ]:
x = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()

print("Python is " + x)

Python is fantastic
Python is awesome

#The global Keyword
Normally, when you create a variable inside a function, that variable is local, and can only be used inside that function.

To create a global variable inside a function, you can use the global keyword.
#Example
If you use the global keyword, the variable belongs to the global scope:

In [ ]:
def myfunc():
  global x
  x = "fantastic"

myfunc()

print("Python is " + x)

Python is fantastic

Also, use the global keyword if you want to change a global variable inside a function.

#Example
To change the value of a global variable inside a function, refer to the variable by using the global keyword:

In [ ]:
x = "awesome"

def myfunc():
  global x
  x = "fantastic"

myfunc()

print("Python is " + x)

Python is fantastic

#Built-in Data Types
In programming, data type is an important concept.

Variables can store data of different types, and different types can do different things.

Python has the following data types built-in by default, in these categories:


Text Type:	str

Numeric Types:	int, float, complex

Sequence Types:	list, tuple, range

Mapping Type:	dict

Set Types:	set, frozenset

Boolean Type:	bool

Binary Types:	bytes, bytearray, memoryview

None Type:	NoneType

#Getting the Data Type
You can get the data type of any object by using the type() function:
#ExampleGet your own Python Server
Print the data type of the variable x:
x = 5
print(type(x))

#Setting the Data Type
In Python, the data type is set when you assign a value to a variable:

In [ ]:
x = "Hello World"	#str
print(x)
x = 20	#int
print(x)
x = 20.5	#float
print(x)
x = 1j	#complex
print(x)
x = ["apple", "banana", "cherry"]	#list
print(x)
x = ("apple", "banana", "cherry")	#tuple
print(x)
x = range(6)	#range
print(x)
x = {"name" : "John", "age" : 36}	#dict
print(x)
x = {"apple", "banana", "cherry"}	#set
print(x)
x = frozenset({"apple", "banana", "cherry"})	#frozenset: frozenset is an immutable version of a Python set. It cannot be modified after creation.
print(x)
x = True	#bool
print(x)
x = b"Hello"	#bytes: b"Hello" creates a bytes object, which is a sequence of bytes (immutable).
print(x)
x = bytearray(5)	#bytearray: bytearray creates a mutable sequence of bytes. Here, it initializes with 5 zero-bytes.
print(x)
x = memoryview(bytes(5))	#memoryview: memoryview allows memory-efficient manipulation of the underlying byte buffer. The memory address may vary depending on your environment.
print(x)
x = None	#NoneType
print(x)

Hello World
20
20.5
1j
['apple', 'banana', 'cherry']
('apple', 'banana', 'cherry')
range(0, 6)
{'name': 'John', 'age': 36}
{'banana', 'apple', 'cherry'}
frozenset({'banana', 'apple', 'cherry'})
True
b'Hello'
bytearray(b'\x00\x00\x00\x00\x00')
<memory at 0x7f9fcc352680>
None

#Python Numbers
There are three numeric types in Python:

* int
* float
* complex

Variables of numeric types are created when you assign a value to them:

In [ ]:
x = 1    # int
y = 2.8  # float
z = 1j   # complex

#To verify the type of any object in Python, use the type() function:
print(type(x))
print(type(y))
print(type(z))

#Int, or integer, is a whole number, positive or negative, without decimals, of unlimited length.

x = 1
y = 35656222554887711
z = -3255522

print(type(x))
print(type(y))
print(type(z))

#Float, or "floating point number" is a number, positive or negative, containing one or more decimals.

x = 1.10
y = 1.0
z = -35.59

print(type(x))
print(type(y))
print(type(z))

#Float can also be scientific numbers with an "e" to indicate the power of 10.

x = 35e3
y = 12E4
z = -87.7e100

print(type(x))
print(type(y))
print(type(z))

#Complex numbers are written with a "j" as the imaginary part:
x = 3+5j
y = 5j
z = -5j

print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'complex'>
<class 'complex'>
<class 'complex'>

#Type Conversion
You can convert from one type to another with the int(), float(), and complex() methods:
#Example
Convert from one type to another:

<font color='red'>Note: You cannot convert complex numbers into another number type.</font>

In [ ]:
x = 1    # int
y = 2.8  # float
z = 1j   # complex

#convert from int to float:
a = float(x)

#convert from float to int:
b = int(y)

#convert from int to complex:
c = complex(x)

print(a)
print(b)
print(c)

print(type(a))
print(type(b))
print(type(c))

1.0
2
(1+0j)
<class 'float'>
<class 'int'>
<class 'complex'>

#Random Number

Python does not have a random() function to make a random number, but Python has a built-in module called random that can be used to make random numbers:

#Example
Import the random module, and display a random number between 1 and 9:

In [ ]:
import random

print(random.randrange(1, 10))

4

#Python Casting
#Specify a Variable Type
There may be times when you want to specify a type on to a variable. This can be done with casting. Python is an object-orientated language, and as such it uses classes to define data types, including its primitive types.

Casting in python is therefore done using constructor functions:

* int() - constructs an integer number from an integer literal, a float literal (by removing all decimals), or a string literal (providing the string represents a whole number)
* float() - constructs a float number from an integer literal, a float literal or a string literal (providing the string represents a float or an integer)
* str() - constructs a string from a wide variety of data types, including strings, integer literals and float literals

In [ ]:
#Integers:

x = int(1)   # x will be 1
y = int(2.8) # y will be 2
z = int("3") # z will be 3

#Floats:

x = float(1)     # x will be 1.0
y = float(2.8)   # y will be 2.8
z = float("3")   # z will be 3.0
w = float("4.2") # w will be 4.2

#Strings:

x = str("s1") # x will be 's1'
y = str(2)    # y will be '2'
z = str(3.0)  # z will be '3.0'

#Python Strings
Strings in python are surrounded by either single quotation marks, or double quotation marks.

'hello' is the same as "hello".

You can display a string literal with the print() function:

Example

In [ ]:
print("Hello")
print('Hello')

#Assign String to a Variable
#Assigning a string to a variable is done with the variable name followed by an equal sign and the string:

#Example

a = "Hello"
print(a)

#Multiline Strings
#You can assign a multiline string to a variable by using three quotes:

#Example
#You can use three double quotes:

a = """Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."""
print(a)

#Or three single quotes:

#Example
a = '''Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.'''
print(a)

Hello
Hello
Hello
Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.
Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.

<font color='red'> Note: in the result, the line breaks are inserted at the same position as in the code.</font>

#Strings are Arrays
Like many other popular programming languages, strings in Python are arrays of bytes representing unicode characters.

However, Python does not have a character data type, a single character is simply a string with a length of 1.

Square brackets can be used to access elements of the string.

#Example
Get the character at position 1 (remember that the first character has the position 0):

In [ ]:
a = "Hello, World!"
print(a[1])

e

#Looping Through a String
Since strings are arrays, we can loop through the characters in a string, with a for loop.

#String Length
To get the length of a string, use the len() function.

#Check String
To check if a certain phrase or character is present in a string, we can use the keyword in.

#Check if NOT
To check if a certain phrase or character is NOT present in a string, we can use the keyword not in.

#Examples

In [ ]:
#Loop through the letters in the word "banana":

for x in "banana":
  print(x)

#The len() function returns the length of a string:

a = "Hello, World!"
print(len(a))


#Check if "free" is present in the following text:

txt = "The best things in life are free!"
print("free" in txt)

#Print only if "free" is present:

txt = "The best things in life are free!"
if "free" in txt:
  print("Yes, 'free' is present.")

#Check if "expensive" is NOT present in the following text:

txt = "The best things in life are free!"
print("expensive" not in txt)

#print only if "expensive" is NOT present:

txt = "The best things in life are free!"
if "expensive" not in txt:
  print("No, 'expensive' is NOT present.")

b
a
n
a
n
a
13
True
Yes, 'free' is present.
True
No, 'expensive' is NOT present.

##Python - Slicing Strings
#Slicing
You can return a range of characters by using the slice syntax.

Specify the start index and the end index, separated by a colon, to return a part of the string.

<font color ="red"> Note: The first character has index 0. </font>

In [ ]:
#Get the characters from position 2 to position 5 (not included):

b = "String slicing operation"
print(b[2:5])


#Get the characters from the start to position 5 (not included):

b = "Hello, World!"
print(b[:5])

'''
By leaving out the end index, the range will go to the end:
Get the characters from position 2, and all the way to the end:
'''

b = "Hello, World!"
print(b[2:])

'''
Use negative indexes to start the slice from the end of the string:
Example
Get the characters:

From: "o" in "World!" (position -5)

To, but not included: "d" in "World!" (position -2):
'''

b = "Hello, World!"
print(b[-5:-2])

rin
Hello
llo, World!
orl

##Python - Modify Strings
Python has a set of built-in methods that you can use on strings.

#Examples

In [ ]:
#The upper() method returns the string in upper case:

a = "Hello, World!"
print(a.upper())


#The lower() method returns the string in lower case:

a = "Hello, World!"
print(a.lower())

'''
Whitespace is the space before and/or after the actual text, and very often you want to remove this space.
The strip() method removes any whitespace from the beginning or the end:
'''

a = " Hello, World! "
print(a.strip()) # returns "Hello, World!"


#The replace() method replaces a string with another string:

a = "Hello, World!"
print(a.replace("H", "J"))

'''
The split() method returns a list where the text between the specified separator becomes the list items.
The split() method splits the string into substrings if it finds instances of the separator:
'''

a = "Hello, World!"
print(a.split(" ")) # returns ['Hello', ' World!']

HELLO, WORLD!
hello, world!
Hello, World!
Jello, World!

'\nThe split() method returns a list where the text between the specified separator becomes the list items.\nThe split() method splits the string into substrings if it finds instances of the separator:\n'

##Python - String Concatenation

To concatenate, or combine, two strings you can use the + operator.

#Examples

In [ ]:
#Merge variable a with variable b into variable c:

a = "Hello"
b = "World"
c = a + b
print(c)

#To add a space between them, add a " ":

a = "Hello"
b = "World"
c = a + " " + b
print(c)

HelloWorld
Hello World

##Python - Format - Strings

As we learned in the Python Variables chapter, we cannot combine strings and numbers like this:

In [ ]:
age = 36
#txt = "My name is John, I am " + age #can only concatenate str (not "int") to str
#print(txt)

#Use the format() method to insert numbers into strings:
age = 36
txt = "My name is John, and I am {}"
print(txt.format(age))

#The format() method takes unlimited number of arguments, and are placed into the respective placeholders:

quantity = 3
itemno = 567
price = 49.95
myorder = "I want {} pieces of item {} for {} dollars."
print(myorder.format(quantity, itemno, price))

#You can use index numbers {0} to be sure the arguments are placed in the correct placeholders:

quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))

My name is John, and I am 36
I want 3 pieces of item 567 for 49.95 dollars.
I want to pay 49.95 dollars for 3 pieces of item 567.

##Python - Escape Characters

#Escape Character
To insert characters that are illegal in a string, use an escape character.

An escape character is a backslash \ followed by the character you want to insert.

An example of an illegal character is a double quote inside a string that is surrounded by double quotes:


Code	Result
\'	Single Quote
\\	Backslash
\n	New Line
\r	Carriage Return
\t	Tab
\b	Backspace
\f	Form Feed
\ooo	Octal value
\xhh	Hex value

#Examples

In [ ]:
txt = "We are the so-called "Vikings" from the north." #SyntaxError: invalid syntax

'''
To fix this problem, use the escape character \":

The escape character allows you to use double quotes when you normally would not be allowed:
'''

txt = "We are the so-called \"Vikings\" from the north."
txt = "We are the so-called '''Vikings''' from the north."

#String Methods
Python has a set of built-in methods that you can use on strings.

<font color="red">Note: All string methods return new values. They do not change the original string.</font>

**Method	        Description**
*  capitalize()	Converts the first character to upper case
*  casefold()	Converts string into lower case
*  center()	Returns a centered string
*  count()	Returns the number of times a specified value occurs in a string
*  encode()	Returns an encoded version of the string
*  endswith()	Returns true if the string ends with the specified value
*  expandtabs()	Sets the tab size of the string
*  find()	Searches the string for a specified value and returns the position of where it was found
*  format()	Formats specified values in a string
*  format_map()	Formats specified values in a string
*  index()	Searches the string for a specified value and returns the position of where it was found
*  isalnum()	Returns True if all characters in the string are alphanumeric
*  isalpha()	Returns True if all characters in the string are in the alphabet
*  isascii()	Returns True if all characters in the string are ascii characters
*  isdecimal()	Returns True if all characters in the string are decimals
*  isdigit()	Returns True if all characters in the string are digits
*  isidentifier()	Returns True if the string is an identifier
*  islower()	Returns True if all characters in the string are lower case
*  isnumeric()	Returns True if all characters in the string are numeric
*  isprintable()	Returns True if all characters in the string are printable
*  isspace()	Returns True if all characters in the string are whitespaces
*  istitle()	Returns True if the string follows the rules of a title
*  isupper()	Returns True if all characters in the string are upper case
*  join()	Joins the elements of an iterable to the end of the string
*  ljust()	Returns a left justified version of the string
*  lower()	Converts a string into lower case
*  lstrip()	Returns a left trim version of the string
*  maketrans()	Returns a translation table to be used in translations
*  partition()	Returns a tuple where the string is parted into three parts
*  replace()	Returns a string where a specified value is replaced with a specified value
*  rfind()	Searches the string for a specified value and returns the last position of where it was found
*  rindex()	Searches the string for a specified value and returns the last position of where it was found
*  rjust()	Returns a right justified version of the string
rpartition()	Returns a tuple where the string is parted into three parts
*  rsplit()	Splits the string at the specified separator, and returns a list
rstrip()	Returns a right trim version of the string
*  split()	Splits the string at the specified separator, and returns a list
*  splitlines()	Splits the string at line breaks and returns a list
*  startswith()	Returns true if the string starts with the specified value
*  strip()	Returns a trimmed version of the string
*  swapcase()	Swaps cases, lower case becomes upper case and vice versa
*  title()	Converts the first character of each word to upper case
*  translate()	Returns a translated string
*  upper()	Converts a string into upper case
*  zfill()	Fills the string with a specified number of 0 values at the beginning


#Some Examples

In [ ]:
str="Hello"
print(str[-5])
str="    Hello World   "
print(str.strip())

H
Hello World

In [ ]:
#Upper case the first letter in this sentence:

txt = "hello, and welcome to my world."

x = txt.capitalize()

print (x)

#Make the string lower case:
txt = "Hello, And Welcome To My World!"

x = txt.casefold()

print(x)

#Print the word "banana", taking up the space of 20 characters, with "banana" in the middle:

txt = "banana"

x = txt.center(20)

print(x)

#Return the number of times the value "apple" appears in the string:

txt = "I love apples, apple are my favorite fruit"

x = txt.count("apple")

print(x)

#UTF-8 encode the string:

txt = "My name is Ståle"

x = txt.encode()

print(x)

#Check if the string ends with a punctuation sign (.):

txt = "Hello, welcome to my world."

x = txt.endswith(".")

print(x)

#Set the tab size to 2 whitespaces:

txt = "H\te\tl\tl\to"

x =  txt.expandtabs(2)

print(x)

#Where in the text is the word "welcome"?:

txt = "Hello, welcome to my world."

x = txt.find("welcome")

print(x)

#Insert the price inside the placeholder, the price should be in fixed point, two-decimal format:

txt = "For only {price:.2f} dollars!"
print(txt.format(price = 49))


#Where in the text is the word "welcome"?:

txt = "Hello, welcome to my world."

x = txt.index("welcome")

print(x)

#Check if all the characters in the text are alphanumeric:

txt = "Company12"

x = txt.isalnum()

print(x)

#Check if all the characters in the text are letters:

txt = "CompanyX"

x = txt.isalpha()

print(x)

#Check if all the characters in the text are ascii characters:

txt = "Company123"

x = txt.isascii()

print(x)

#Check if all the characters in a string are decimals (0-9):

txt = "1234"

x = txt.isdecimal()

print(x)

#Check if all the characters in the text are digits:

txt = "50800"

x = txt.isdigit()

print(x)

Hello, and welcome to my world.
hello, and welcome to my world!
       banana
2
b'My name is St\xc3\xa5le'
True
H e l l o
7
For only 49.00 dollars!
7
True
True
True
True
True

##Python Booleans

Booleans represent one of two values: True or False.

#Boolean Values
In programming you often need to know if an expression is True or False.

You can evaluate any expression in Python, and get one of two answers, True or False.

When you compare two values, the expression is evaluated and Python returns the Boolean answer:

In [ ]:
print(10 > 9)
print(10 == 9)
print(10 < 9)

#When you run a condition in an if statement, Python returns True or False:
#Print a message based on whether the condition is True or False:

a = 200
b = 33

if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")


#The bool() function allows you to evaluate any value, and give you True or False in return,

print(bool("Hello"))
print(bool(15))

#Evaluate two variables:

x = "Hello"
y = 15

print(bool(x))
print(bool(y))

#Most Values are True
Almost any value is evaluated to True if it has some sort of content.

Any string is True, except empty strings.

Any number is True, except 0.

Any list, tuple, set, and dictionary are True, except empty ones.

In [ ]:
#The following will return True:

#bool("abc")
bool(123)
#bool(["apple", "cherry", "banana"])

True

#Some Values are False
In fact, there are not many values that evaluate to False, except empty values, such as (), [], {}, "", the number 0, and the value None. And of course the value False evaluates to False.

In [ ]:
#The following will return False:

bool(False)
bool(None)
bool(0)
bool("")
bool(())
bool([])
bool({})

#One more value, or object in this case, evaluates to False, and that is if you have an object that is made from a class with a __len__ function that returns 0 or False:

class myclass():
  def __len__(self):
    return 0

myobj = myclass()
print(bool(myobj))

False

#Functions can Return a Boolean
You can create functions that returns a Boolean Value:

In [ ]:
def myFunction() :
  return True

print(myFunction())

#You can execute code based on the Boolean answer of a function: Print "YES!" if the function returns True, otherwise print "NO!":

def myFunction() :
  return True

if myFunction():
  print("YES!")
else:
  print("NO!")


#Python also has many built-in functions that return a boolean value, like the isinstance() function, which can be used to determine if an object is of a certain data type:
#Check if an object is an integer or not:

x = 200
print(isinstance(x, int))

##Python Operators

Operators are used to perform operations on variables and values.

In the example below, we use the + operator to add together two values:


Python divides the operators in the following groups:

Arithmetic operators

Assignment operators

Comparison operators

Logical operators

Identity operators

Membership operators

Bitwise operators

#Arithmetic operators
Arithmetic operators are used to perform arithmetic calculations in python. Below are the arithmetic operators with names and their symbols. These are the symbols that we use while doing an arithmetic operation in python.

In [ ]:
x = 10
y = 15
#addition
print(x + y)
#subtraction
print(x - y)
#multiplication
print(x * y)
#division
print(x / y)
#floor division
print(x // y)
#modulus
print(x % y)
#exponentiation
print(x ** y)

25
-5
150
0.6666666666666666
0
10
1000000000000000

#Assignment operators
Assignment operators are used to assign values to the variables or any other object in python. Following are the assignment operators that we have in python.

In [ ]:
x = 10
x += 5
print(x)
#it is same as x = x + 5
x -= 5
print(x)
x *= 5
print(x)
x /= 5
print(x)
#similarly we can write all assignment operators like this.

15
10
50
10.0

#Comparison operators
Comparison operators are used to compare two values. Following are the comparison operators that we have in python.

In [ ]:
x = 5
y = 3

#equal
x == 5

#not equal
x != 5

#greater than
x > y

#less than
x < y
#greater than or equal to
x >= y

#less than or equal to
x <= y

False

#Logical operators
Logical operators are used to compare two conditional statements. Following are the logical operators that we have in python.

In [ ]:
#logical and
5 > 3 and 5 > 4
#it will return true, since both statements are true.
5 > 3 or 5 < 2
#it will return true, since one of the statements is true.
not(5 > 2 and 5 < 3)
#it will return true, even when logical and will return false.

True

#Identity operators
Identity operators compare two objects. Following are the identity operators that we have in python.

In [ ]:
a = [10,20,30]
b = [10,20,30]
x = b
z = a
# is operator
print(x is b)
#this will return false
print(x is z)
#this will return false.
print(a is b)
#this will return false, even though both have the same items in the list.
print(a is not b)
#this will return true, since both are not same objects.

True
False
False
True

#Membership operators
Membership operators are used to check if a sequence is present in an object. Following are the membership operators that we have in python.

In [ ]:
a = [10,20,30,'Hello']
#in operator
print('Hello' in a)
#this will return true, since the item is present in the object.
print('python' in a)
#this will return false, since it is not present in a.
print(10 not in a)
#this will return false, because it is there.
print(50 not in a)
#this will return true, since there is no 50 in a.

True
False
False
True

#Bitwise operators
Bitwise operators compare the binary values. Following are the bitwise operators that we have in python.

To understand how we got the result using the bitwise operators lets take a look at the binary equivalent of 10 and 12.

10 in binary is 1010 and 12 in binary is 1100. When doing an AND operation between 1010 and 1100, the bit will be 1 if both the bits are 1. Therefore, the resultant binary equivalent will be 1000 which is 8 when we convert it to decimal.

Bitwise OR operator will set each bit to 1 if one of the bits is 1, bitwise XOR will set each bit to 1 if only one of the bits is 1 and bitwise not will invert all bits.

When doing a left shift or a right shift, the bits will shift left 2 places in our example. Therefore 1010 will become 101000 which is 40. Similarly, when doing right shift 1010 will become 10, which is 2.

In [ ]:
#bitwise AND
print(10 & 12)
#this will return 8
#bitwise OR
print(10 | 12)
#this will return 14
#bitwise XOR
print(10 ^ 12)
#this will return 6
#bitwise NOT
print(~ (10 ))
#this will return -9
#left shift
print(10 << 2) #this will return 40
#right shift
print(10 >> 2)
#this will return 2

8
14
6
-11
40
2

#What Is A List In Python?
List is a collection data type in python. It is ordered and allows duplicate entries as well. Lists in python need not be homogeneous, which means it can contain different data types like integers, strings and other collection data types. It is mutable in nature and allows indexing to access the members in a list.

To declare a list, we use the square brackets.

List is like any other array that we declare in other programming languages. Lists in python are often used to implement stacks and queues. The lists are mutable in nature. Therefore, the values can be changed even after a list is declared.

#Why Use A List?
While choosing a data type for storing our data, we must keep in mind the properties and features of the data type. It becomes more efficient and secure if we make the right choice in first place.

A list is preferred because it can store multiple data at the same time. It becomes easy to replace and modify the values inside a list. We can store the sequence in a list and perform several iterations using the loops as well. There are numerous operations we can perform on a list as well, lets understand the various operations that we have for lists in python.

List Operations In Python
Following are the operations that we can perform on a list.

* append
* clear
* copy
* count
* extend
* insert
* index
* pop
* remove
* reverse
* sort

In [ ]:
mylist = [0,1,2,3,4,5,6]

a = ['H', 'E', 'L', 'L', 'O', 'C', 'L','A','S','S']

print(a[6])

print(a[-1])

L
S

In [ ]:
a = [1,1,1,3,3,'a',4,4,4,4,5,5,5,5,5]
print(a.index(4))

6

In [ ]:
a = [5,4,3,2,1]
a = a[: :-1]
print(a)

[1, 2, 3, 4, 5]

In [ ]:
#append
#the output will have 6 at the end of the list.
1
2
3
4
a = [1,2,3,4,5]
a.append(6)
print(a)


#clear
#this will clear the list or empty the list.
1
2
3
4
a = [1,2,3,4,5]

a.clear()

#copy
#it makes the copy of the list.
1
2
3
4
5
a = [1,2,3,4,5]
b = a.copy()

print(b)

#count
#this will give the number of times 5 is present in the list.
1
2
3
4
a = [1,1,1,3,3,3,4,4,4,4,5,5,5,5,5]
a.count(5)

#extend
#this will add the values in this list from the iterable object range.
1
2
3
4
a = [1,2,3,4,5]

a.extend(range(6,11))

#insert
#this will add the string at the index value 2
1
2
3
4
a = ['ml', 'python', 'data science']
a.insert(2,'artificial intelligence')

#index
#this will get the index value at the string 'data science' which is 3.
1
2
3
4
a = ['Deep learning ', 'python', 'programming', 'data science', 'AI', 'machine learning']
a.index('data science')


#pop
#this will pop the value from the  end of the list i.e 5. the list will no longer have 5 after this.
1
2
3
4
a = [1,2,3,4,5]
a.pop()

#remove
#this will remove 11 from the list.
1
2
3
4
a = [1,2,3,4,11,5]

a.remove(11)

#reverse
#this will reverse the list.
1
2
3
4
5
6
7
a = [5,4,3,2,1]

a.reverse()


#another statement to reverse the list
a = [5,4,3,2,1]
a = a[: :-1]
print(a)
#sort

1
2
3
4
a = [3,1,2,6,4,5,9,6,7,8]

a.sort()
#you will get a sorted list as a result.
#Replacing a value in a list

1
2
3
4
a = ['deep learning', 'python', 'data science', 'tennis', 'machine learning']

a[3] = 'artificial intelligence'
#this will replace the value at the given index with the mentioned value.
#Iterate through a list

#Lists can be used for iterations as well. Below is the code to iterate a list and print values using a control statement.

1
2
3
4
5
6
7
a = ['a','b','c','d','e']

for x in a: #for(i=0;i<5;i++)
    if x == 4:
         break   #print(a[i])
print(x)
#this will iterate through the list and print the values until it encounters 4.

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
e

In [ ]:
a = ['a','b','c','d','e']

for x in a: #for(i=0;i<5;i++)
   print(x)

for x in a: #for(i=0;i<5;i++)
   if x == 4:
         break
print(x)

a
b
c
d
e
e

#The List Constructor

The list constructor is used to create/declare a list.

As you can see, the list constructor takes the tuple as argument. Similarly, you can declare any other data type like a dictionary or a set inside the list constructor as well.

In [ ]:
a = list((1,2,3,4,5))

print(a)
#you will get a list with the values declared in the constructor.

[1, 2, 3, 4, 5]

#Slicing A List In Python
Suppose you have a list with numbers from 0-10. But you only want to get the numbers from 5-10, you must not access all the elements typing the index values of all those numbers. Instead you can follow the approach in the code below.

In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]

print(a[4:11])
#this will get all the numbers starting from index 4 to index 11.

print(a[-7:-1])
#this will get all the numbers from the index 11 to index 6.

print(a[4:])
#this will print all the numbers starting from index 4 until the end of the list.

print(a[:6])
#this will print all the numbers from index 0 until the index 6.

[5, 6, 7, 8, 9, 10]
[4, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6]

#Subsetting A List In Python
Subsetting a list means, declaring a list inside an existing list.

Instead of a list, we can use any other data type as well. But since a set is unindexed, it will not be possible to access the set items separately using the index values.

In [ ]:
a = list(range(5,11))

b = [1,2,3,4, a ] #[1,2,3,4, [5,6,7,8,9,10]]

#to access a value in the list

print(b[4])

#this will print the list a.

print(b[4][4])

#this will get the value at the index value 4 in the list a.

b[4][4] = 19
print(b[4][4])
print(b)
#we can change the values  as well, replace, delete modify etc.

[5, 6, 7, 8, 9, 10]
9
19
[1, 2, 3, 4, [5, 6, 7, 8, 19, 10]]

#What Is A Tuple?
A tuple is an immutable data type in python, almost similar to a list in python in terms of indexing and having duplicate members. It is a collection data type that stores python objects separated by commas. Following is an example of how we can create or declare a tuple in python.

#Accessing Items In A Python Tuple
Accessing items in a tuple works similar to a list, we can access elements in a list using indexes. We can specify the index value and it will return the item stored at that particular index value.

#Indexing
It is a data structure technique to effectively retrieve information from a data structure. In python, several data types support indexing like lists, string, etc.

For example, let’s just say we have a tuple with 5 natural numbers as members. So the indexing will start with the value 0 where 1 will be stored and it will go until the end of the tuple i.e 5 and the index value at 5 will be 4.

Take a look at the example below to understand how we can access elements in a python tuple using indexing

In [ ]:
#creating a tuple
a = ('python', 'programming')
#another approach
b = 'python' , 'programming'
print(a)
print(b)

a = ('deep learning', 'python' , 'data structure' , 'collections')
print(a[1])
print(a[3])

('python', 'programming')
('python', 'programming')
python
collections

# Tuple Negative Indexing
In python, we can use negative indexing as well to access elements in a tuple or any other data type that supports indexing.

In [ ]:
a = (1,2,3,4,5,6,7,8,9,10)
print(a[-4])
print(a[-1])

7
10

#Slicing
It is a technique in which we use the slicing operator ‘:’ to get a range of elements from a python tuple or any other data type that supports indexing for accessing elements.

In the below Python Tuple example, the index value before the slicing operator is the starting index and the index value after the slicing operator is the value that will not be included in the output.

Only until the value before the ending index will be included in the output. We can even use the negative index values with the slicing operator to get the range of values from the tuple.

In [ ]:
a = (1,2,3,4,5,6,7,8,9,10)
print(a[1:8])
print(a[1:])
print(a[:5])

(2, 3, 4, 5, 6, 7, 8)
(2, 3, 4, 5, 6, 7, 8, 9, 10)
(1, 2, 3, 4, 5)

#Changing A Python Tuple
Even though tuples in python are immutable in nature, a nested object in a tuple can be changed. Or in general, a python tuple can be reassigned with a different value.

In [ ]:
a = (1,2,3,[4,5])
a[3][0] = 14
print(a)
#reassigning the value
a = ('VSITR', 'python')
print(a)

(1, 2, 3, [14, 5])
('VSITR', 'python')

#Concatenating Two Tuples
Joining two tuples is a very easy task. You just to assign the addition of the two tuples to another variable and it will return the concatenated tuple with the values of both the tuples. Consider the example below to understand this.

In [ ]:
a = (1,2,3,4,5)
b = (6,5,8,9,10)
c = a + b
print(c)

(1, 2, 3, 4, 5, 6, 5, 8, 9, 10)

#Deleting A Python Tuple
Being an immutable data type, a tuple in python does not allow any changes and you cannot even remove an element from a tuple after the declaration. But there is a keyword ‘del’ which will delete the tuple altogether.

You will get a Name error if you run the above program because there is no tuple named as present since we have deleted it.

In [ ]:
a = (1,2,3,4,5)
del a
print(a)

NameError: name 'a' is not defined

##Tuple Methods
Following are the tuple methods that we can use while working with a tuple in python.

* count: Returns the count of the items.

* index: It returns the index of the item specified.

In [ ]:
a = (1,2,1,3,1,3,1,2,1,4,1,5,1,5)
print(a.count(1))
print(a.index(5))

#Iterating Through A Python Tuple
Using a for loop we can iterate through a tuple in python.

The following example shows how we can iterate through a tuple using a for loop.

In [ ]:
a = ("VSITR", "for data science", "for Artificial Intelligence")
for i in a:
    print("python", i)

python VSITR
python for data science
python for Artificial Intelligence

#Python Tuple Constructor
It is possible to create a tuple using a tuple() constructor as well. We can even use the tuple constructor to change a list to a tuple.

In [ ]:
a = [1,2,3,4,5]
b = tuple(a)
print(b)
c = tuple(('VSITR', 'python'))
print(c)

(1, 2, 3, 4, 5)
('VSITR', 'python')

#Membership Test In A Tuple
Using the membership operator ‘in’ in python we can check whether an element is present in a tuple or not. The following example shows how we can check if an element is present in a tuple or not.

In [ ]:
a = (1,2,3,4,5,6,7,8,9,10)

print(6 in a)

print(15 in a )

True
False

#List vs Tuple


<table border="1">
  <tr>
    <th>List</th>
    <th>Tuple</th>
  </tr>
  <tr>
    <td>Used for homogenous data types (same data types values)</td>
    <td>Generally used for heterogeneous data types (different data types values)</td>
  </tr>
  <tr>
    <td>Mutable in nature</td>
    <td>Immutable in nature, which helps in faster iteration</td>
  </tr>
  <tr>
    <td>Does not have immutable elements</td>
    <td>Immutable elements can be used as a key for a dictionary</td>
  </tr>
  <tr>
    <td>No guarantee that the data is write-protected</td>
    <td>Implementing a tuple with data that does not change guarantees that it is write-protected</td>
  </tr>
</table>

#What is Set in Python?
A set is basically a data type consisting of a collection of unordered elements. These elements can be on any data types as sets, unlike arrays, are not type specific. Sets are mutable(changeable) and do not have repeated copies of elements. The values of a set are unindexed, therefore, indexing operations cannot be performed on sets.

The output shows all the elements present My_Set.

<font color="red">Note: A set as a whole is mutable but the elements of a set are not.</font>

Now that you know what are sets in Python, let’s move ahead and understand when to use sets.


#When to use sets in Python?
Sets in Python are used when-

The order of data does not matter
You do not need any repetitions in the data elements
You need to perform mathematical operations such as union, intersection, etc
Now let us move ahead and see how to create sets in Python.

#How do you create a set in Python?
Sets in Python can be created in two ways-

enclosing elements within curly braces by using the set() function

In [ ]:
My_Set={11,3.4,2,3,5.6}
print(My_Set)

{2, 3, 3.4, 5.6, 11}

In [ ]:
#1.Using curly braces:

#Sets in Python are created using curly braces({}).

a={1,'b',6.9}
print(a)

#2. Using set() function
#Sets in Python can be created using the set() function.

a=set({1,'b',6.9})
print(a)

#You can also create an empty set using the same function.

Empty_Set=set()
print(Empty_Set)

{1, 'b', 6.9}
{1, 'b', 6.9}
set()

#Set Operations
A number of operations can be performed on sets such as adding elements, deleting elements, finding the length of a set, etc. To know what all methods can be used on sets, you can use the dir() function.

In [ ]:
My_Set={1,'s',7.8}
dir(My_Set)

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

#Finding the Length of a Set
To find the length of a set in Python, you can use the len() function. This function takes the name of the set as a parameter and returns an integer value which is equal to the number of elements present in the set.

In [ ]:
My_Set={1,'s',7.8}

len(My_Set)

3

#Accessing Elements of a Set
Set elements cannot be accessed using the index numbers because, as specified before, elements of a set are not indexed. Therefore, when you want to access elements of a set, you can loop through it and access its elements.

In [ ]:
My_Set={1,'s',7.8}
for x in My_Set:
    print(x)

1
s
7.8

#Adding elements to a Set:
Elements can be added to a set using two functions, the add() and the update() function.

The add() function adds one element to the existing set as shown below:

In [ ]:
My_Set={1,'s',7.8}
My_Set.add(3)
My_Set.add('a')
My_Set.add(2.5)
My_Set

{1, 2.5, 3, 7.8, 'a', 's'}

#Removing Elements of a Set
To remove elements from a set, you can use either the remove(), discard() and the pop() functions.

The remove() function takes one parameter which is the item to be removed from the set.

In [ ]:
My_Set={1, 2, 4.6, 7.8, 'r',2, 's', 2}
My_Set.remove(2)
print(My_Set)

{1, 4.6, 7.8, 's', 'r'}

As you can see, 2 has been removed from the set using the remove() function. In case you specify some element as a parameter to remove() that does not exist in the set, it will throw an error.

Now, if you want to remove some element from the set, and if you are not sure whether that element is actually present in the set or not, you can use the discard() function. This function will take the element to be removed from the set as a parameter but in case the element is not present, it does not throw an error.

In [ ]:
My_Set={1, 2, 4.6, 7.8, 'r', 's'}
My_Set.discard(4.6)
print(My_Set)
My_Set.discard('i')
print(My_Set)

{1, 2, 'r', 7.8, 's'}
{1, 2, 'r', 7.8, 's'}

The above output shows that 4.6 has been removed from My_Set but discard() has not thrown an error when I used My_Set.discard(‘i’) even though ‘i’ is not present in my set.

The pop() function also removes set elements, but since a set is unordered, you will not know which element has been removed.

In [ ]:
My_Set={ 2, 4.6, 7.8, 'r', 's'}
My_Set.pop()
print(My_Set)

#Now, in case you want to delete all elements present in a set, you can use the clear() method.

My_Set={1, 2, 4.6, 7.8, 'r', 's'}
My_Set.clear()
print(My_Set)


#As you can see in the above output, My_Set is an empty set.

#In case you want to completely delete the set, you can use the del keyword.
My_Set={1, 2, 4.6, 7.8, 'r', 's'}
del My_Set
#print(My_Set)

{2, 4.6, 7.8, 's'}
set()

#Union of Sets
Union of sets refers to the concatenation of two or more sets into a single set by adding all unique elements present in both sets. This can be done in two ways:

#Using pipeline
Using union() function

#Using pipeline symbol:

Two sets can be concatenated using the | symbol as follows:

In [ ]:
a={1, 2, 4.6, 7.8, 'r', 's'}
b={2,5,'d','abc'}
c=a|b
print(a|b)


#As you can see, in the above output, a union of set a and set b is stored in a new set c. You can concatenate more than two sets as well using | symbol.

a={1, 2, 4.6, 7.8, 'r', 's'}
b={2,5,'d','abc'}
c={2,3,4,5}
d=a|b|c
print(d)

{1, 2, 'd', 4.6, 5, 7.8, 'abc', 'r', 's'}
{1, 2, 'd', 4.6, 5, 3, 7.8, 4, 'abc', 'r', 's'}

#Using the union() method:

To concatenate two or more sets, you can use the union() method as follows:

In [ ]:
a={1, 2, 4.6, 7.8, 'r', 's'}
b={2,5,'d','abc'}
c={'m',23,76,4.7}
print("Set a U b = ",a.union(b))
print("Set a U b U c = ",a.union(b,c))

Set a U b =  {1, 2, 'd', 4.6, 5, 7.8, 'abc', 'r', 's'}
Set a U b U c =  {1, 2, 'd', 4.6, 5, 4.7, 7.8, 76, 'abc', 'm', 'r', 23, 's'}

#Intersection of Sets

The intersection of two or more sets is a new set consisting of only the common elements present in those sets.

#This can be done in two ways:

* Using ‘&’ symbol
* Using intersection() function

#Using ‘&’ symbol:

You can determine the intersection of two or more sets using the ‘&’ symbol as follows:

In [ ]:
a={1, 2,5, 4.6, 7.8, 'r', 's'}
b={2,5,'d','abc'}
c={2,3,4,}
print(a&b)
print(a&b&c)

{2, 5}
{2}

#Using intersection() function:

You can determine the intersection of two or more sets using the intersection() function as follows:

In [ ]:
a={1, 2,5, 4.6, 7.8, 'r', 's'}
b={2,5,'d','abc'}
c={2,3,4}
print("Set a intersection b = ",a.intersection(b))
print("Set a intersection b intersection c = ",a.intersection(b,c))

Set a intersection b =  {2, 5}
Set a intersection b intersection c =  {2}

#Difference of Sets:
The difference of sets produces a new set consisting of elements that are present only in one of those sets. This means that all elements except the common elements of those sets will be returned.

#This can be done in two ways:

* Using the ‘-‘ symbol
* Using difference() function
#Using the ‘-‘ symbol:
To find the difference of two sets using ‘-‘ symbol, you can do as follows:

In [ ]:
a={1, 2,5, 4.6, 7.8, 'r', 's'}
b={2,5,'d','abc'}
c={2,3,4}
print(a-b-c)

{1, 4.6, 7.8, 'r', 's'}

#Using the difference() function:
The difference of sets can be determined using the built-in difference() function as follows:

In [ ]:
a={1, 2,5, 4.6, 7.8, 'r', 's'}
b={2,5,'d','abc'}
c={2,3,4}
print("Set a - b = ",a.difference(b))
print("Set a - b - c = ",a.difference(b,c))

Set a - b =  {1, 4.6, 7.8, 'r', 's'}
Set a - b - c =  {1, 4.6, 7.8, 'r', 's'}

#What is a frozen set?

A frozen set in Python is a set whose values cannot be modified. This means that it is immutable unlike a normal set which I have discussed previously. Frozen sets help serve as a key in dictionary key-value pairs.

#How to create frozen sets?
Frozen sets can be obtained using the frozenset() method. This function takes any iterable items and converts it to immutable.

In [ ]:
a={1, 2,5, 4.6, 7.8, 'r', 's'}
b=frozenset(a)
print(b)

#Elements of a frozen set can be accessed by looping through it as follows:
#b[1]=3
b=frozenset([1, 2, 5, 7.8, 'r', 's'])
for x in b:
  print(x)

frozenset({1, 2, 'r', 4.6, 5, 7.8, 's'})
1
2
5
7.8
r
s

#What Is A Dictionary In Python?
It is a collection data type just like a list or a set, but there are certain features that make python dictionary unique. A dictionary in python is not ordered and is changeable as well. We can make changes in a dictionary unlike sets or strings which are immutable in nature. Dictionary contains key-value pairs like a map that we have in other programming languages. A dictionary has  indexes. Since the value of the keys we declare in a dictionary are always unique, we can use them as indexes to access the elements in a dictionary.

Also, a dictionary does not have any duplicate members. Although the value elements in the key value pairs can contain duplicate values.

#Why Use A Dictionary In Python?
First of all, it is not like any other object or data type in python programming language. A dictionary has key value pairs resembling a map. It is often used for unordered data with distinct key values.

It is similar to a real life dictionary. We have distinct keys which we can use to fetch the values specified in them. In case of dictionary, even though there are no duplicate members, we can mention duplicate members in the value elements. Now that we know, why we use a dictionary, lets try to understand how it is different from lists in python.

#Lists vs Dictionary

<table border="1">
  <tr>
    <th>Lists</th>
    <th>Dictionary</th>
  </tr>
  <tr>
    <td>Ordered</td>
    <td>Not ordered</td>
  </tr>
  <tr>
    <td>Access elements use index values</td>
    <td>Access elements use keys as index values</td>
  </tr>
  <tr>
    <td>Collection of elements</td>
    <td>Collection of key-value pairs</td>
  </tr>
  <tr>
    <td>Allows duplicate members</td>
    <td>No duplicate members</td>
  </tr>
  <tr>
    <td>Preferred for ordered data</td>
    <td>Preferred for data with unique key values</td>
  </tr>
</table>

#How To Implement A Dictionary?
To declare a dictionary in python, we use the curly brackets. The keys and values are separated with a colon and the pairs are separated with a comma.

In [ ]:
mydictionary = { 'key1' : 'value1' , 'key2': 'value2' , 'key3': 'value3'}
print(mydictionary)
#Operations In A Python Dictionary

#Accessing an element

mydictionary = { 1: 'DL' , 2: 'python' , 3: 'data science'}
mydictionary[1]
#this will get the key value pair with the key 1.
mydictionary.get(1)
#this is another function which will serve the same purpose.

#Replacing an element

mydictionary = { 1: 'DL', 2: 'python' , 3: 'data science'}
mydictionary[3] = 'artificial intelligence'
print(mydictionary)
#this will replace the value at key 3 to artificial intelligence.

#Removing an element
mydictionary = { 1:'VSITR' , 2 : 'python', 3: 'data science'}
del mydictionary[3]
print(mydictionary)
#this will remove the key value pair from the dictionary with the specified key.

{'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
{1: 'DL', 2: 'python', 3: 'artificial intelligence'}
{1: 'VSITR', 2: 'python'}

#Other Operations

Following are the operations we have for dictionary in python:

* clear()
* copy()
* values()
* update()
* fromkeys()
* get()
* items()
* keys()
* pop()
* popitem()
* setdefault()

In [ ]:
#clear( ) – removes all the elements from the dictionary.

a = { 1: 2 , 2: 3 , 3: 5}
a.clear()
print(a)
#you will get a empty dictionary as the output.

#copy( ) – returns a copy of the dictionary.

a = {1:2, 2: 3, 3: 4}
b = a.copy()
print(b)
#b will be a copy of the dictionary a.

#values( ) – returns all the values in a dictionary.

a = {1: 2, 2: 3, 3:4}
a.values( )
#this will get you the list of all the values in the dictionary.

#update( ) – it updates the values of the dictionary with the specified key value pairs.

1
2
3
a = {1 : 2, 2: 3, 3: 5}
a.update({4: 6})
#this will update the dictionary with the specified key value pair.

#fromkeys( ) – returns a dictionary with the specified keys and values.

a = {1: 'ML' , 2: 'data science'}
b = {1: 2, 2: 3, 3: 'python'}
a.Fromkeys(b)

#this will get the dictionary with the specified keys and values.

#items( ) – returns the list for a tuple of each key value pair in the dictionary.

a = {1: 'VSITR', 2; 'python'}
a.items()
#this will get the list of tuple for each key value pair.

#keys( ) – returns a list containing all the keys in the dictionary.

a = { 1: 'VSITR' , 2 : 'python' , 3 : 'data science'}
a.keys()
#this will get the list of all the keys from the dictionary.

#pop( ) – removes the element with the specified key.

a = { 1: 'VSITR' , 2: 'data science' , 3: 'python' }
a.pop(3)


#this will remove the value 'python' from the dictionary.

#popitem( ) – removes the last inserted key values pair from the dictionary.

a = { 1: 'VSITR' , 2: 'python' , 3: 'data science'}
a.popitem()
#this will remove the last inserted key value pair from the dictionary.

#setdefault( ) – returns the value of the specified key, if not present insert the key with the specified value.
a = { 1: 'VSITR' , 2: 'python' }
a.setdefault(1, 'VSITR')
Dict( ) constructor

#Dictionary constructor is used to declare a dictionary in python.
a = dict( 1= 'VSITR' , 2= 'python' , 3= 'data science')
print(a)
#this will declare a dictionary with the name a and specified key value pairs.

SyntaxError: ':' expected after dictionary key (<ipython-input-1-6f0ce1b12018>, line 40)

#Use Case – Nested Dictionary
Nested dictionary is nothing but a dictionary which incorporates another dictionary. Let us implement a dictionary where we have the statistical data for all the Indian batsmen. We will implement a dictionary with the batsmen names and incorporate other dictionary with the statistics inside the same dictionary to make it a nested dictionary. We will also use the pandas library to get the stats into a dataframe for better understanding.

Below code will print the data frame of the stats of the batsmen from the dictionary. Similarly, you can make this dictionary for bowlers, all rounders and wicket keepers to practice the implementation of nested dictionary.

In [ ]:
import pandas as pd
squad = {'Batsmen': {'Rohit Sharma': {'Matches': 206,
                                      'Runs': 8010,
                                      'Average':47.4,
                                      'Highest Score': 264 },
                     'Shikhar Dhawan': {'Matches':128,
                                        'Runs': 5355,
                                        'Average': 44.62,
                                        'Highest Score': 143},
                     'Virat Kohli': {'Matches': 227,
                                     'Runs': 10843,
                                     'Average': 59.58,
                                     'Highest Score': 183}}
df = pd.DataFrame(squad['Batsmen'])
print(df)

#Python Conditions and If statements
Python supports the usual logical conditions from mathematics:

* Equals: a == b
* Not Equals: a != b
* Less than: a < b
* Less than or equal to: a <= b
* Greater than: a > b
* Greater than or equal to: a >= b
* These conditions can be used in several ways, most commonly in "if statements" and loops.

An "if statement" is written by using the if keyword.

<font color="red"> Point to be remember: Python relies on indentation (whitespace at the beginning of a line) to define scope in the code. Other programming languages often use curly-brackets for this purpose.</font>

In [ ]:
a = 33
b = 200
if b > a:
  print("b is greater than a")

#Elif
The elif keyword is Python's way of saying "if the previous conditions were not true, then try this condition".

In [ ]:
a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

#Else
The else keyword catches anything which isn't caught by the preceding conditions.

In [ ]:
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

#Short Hand If
If you have only one statement to execute, you can put it on the same line as the if statement.

In [ ]:
if a > b: print("a is greater than b")

#Short Hand If ... Else
If you have only one statement to execute, one for if, and one for else, you can put it all on the same line:

This technique is known as **Ternary Operators, or Conditional Expressions.**

You can also have multiple else statements on the same line:

In [ ]:
a = 2
b = 330
print("A") if a > b else print("B")


#One line if else statement, with 3 conditions:
a = 330
b = 330
print("A") if a > b else print("=") if a == b else print("B")

#if a > b
#	print("A")
#else
#	if a == b
#		print("=")
#	else
#		print("B")

#And
#The and keyword is a logical operator, and is used to combine conditional statements:
a = 200
b = 33
c = 500
if a > b and c > a:
  print("Both conditions are True")


#Or
#The or keyword is a logical operator, and is used to combine conditional statements:

a = 200
b = 33
c = 500
if a > b or a > c:
  print("At least one of the conditions is True")

#Not
#The not keyword is a logical operator, and is used to reverse the result of the conditional statement:

a = 33
b = 200
if not a > b:
  print("a is NOT greater than b")

#Nested If
#You can have if statements inside if statements, this is called nested if statements.
x = 41

if x > 10:
  print("Above ten,")
  if x > 20:
    print("and also above 20!")
  else:
    print("but not above 20.")

B
=
Both conditions are True
At least one of the conditions is True
a is NOT greater than b
Above ten,
and also above 20!

#The pass Statement
if statements cannot be empty, but if you for some reason have an if statement with no content, put in the pass statement to avoid getting an error.

In [ ]:
a = 33
b = 200

if b > a:
  pass

#Python Loops
Python has two primitive loop commands:

<li>while loops
<li>for loops

##The while Loop
With the while loop we can execute a set of statements as long as a condition is true.

<font color="red">Note: remember to increment i, or else the loop will continue forever.</font>

In [ ]:
#Print i as long as i is less than 6:

i = 1
while i < 6:
  print(i)
  i += 1

#The break Statement
With the break statement we can stop the loop even if the while condition is true:

In [ ]:
#Exit the loop when i is 3:
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3

#The continue Statement
With the continue statement we can stop the current iteration, and continue with the next:

In [ ]:
#Continue to the next iteration if i is 3:

i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

1
2
4
5
6

#The continue Statement
With the continue statement we can stop the current iteration, and continue with the next:

In [ ]:
#Continue to the next iteration if i is 3:

i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

#The else Statement
With the else statement we can run a block of code once when the condition no longer is true:

In [ ]:
#Print a message once the condition is false:

i = 1
while i < 6:
  print(i)
  i += 1
else:
  print("i is no longer less than 6")

#Python For Loops
A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).

This is less like the for keyword in other programming languages, and works more like an iterator method as found in other object-orientated programming languages.

With the for loop we can execute a set of statements, once for each item in a list, tuple, set etc.

In [ ]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

#Looping Through a String
Even strings are iterable objects, they contain a sequence of characters:

In [ ]:
#Loop through the letters in the word "banana":

for x in "banana":
  print(x)

#The break Statement
With the break statement we can stop the loop before it has looped through all the items:

In [ ]:
#Exit the loop when x is "banana":

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
  if x == "banana":
    break

#Exit the loop when x is "banana", but this time the break comes before the print:

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    break
  print(x)

#The continue Statement
With the continue statement we can stop the current iteration of the loop, and continue with the next:

In [ ]:
#Do not print banana:

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue
  print(x)

#The range() Function
To loop through a set of code a specified number of times, we can use the range() function,
The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number.

<font color="red">Note that range(6) is not the values of 0 to 6, but the values 0 to 5.</font>

In [ ]:
for x in range(6):
  print(x)

#Using the start parameter:

for x in range(2, 6):
  print(x)

#Increment the sequence with 3 (default is 1):

for x in range(2, 30, 3):
  print(x)

#Else in For Loop
The else keyword in a for loop specifies a block of code to be executed when the loop is finished:

<font color="red">Note: The else block will NOT be executed if the loop is stopped by a break statement.</font>

In [ ]:
#Print all numbers from 0 to 5, and print a message when the loop has ended:

for x in range(6):
  print(x)
else:
  print("Finally finished!")

#Break the loop when x is 3, and see what happens with the else block:

for x in range(6):
  if x == 3: break
  print(x)
else:
  print("Finally finished!")

#Nested Loops
A nested loop is a loop inside a loop.

The "inner loop" will be executed one time for each iteration of the "outer loop":

In [ ]:
#Print each adjective for every fruit:

adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y)

#The pass Statement
for loops cannot be empty, but if you for some reason have a for loop with no content, put in the pass statement to avoid getting an error.

In [ ]:
for x in [0, 1, 2]:
  pass

#Python Functions
A function is a block of code which only runs when it is called.

You can pass data, known as parameters, into a function.

A function can return data as a result.

#Creating a Function
In Python a function is defined using the def keyword:

In [ ]:
def my_function():
  print("Hello from a function")

#Calling a Function
To call a function, use the function name followed by parenthesis:

In [ ]:
def my_function():
  print("Hello from a function")

my_function()

#Arguments
Information can be passed into functions as arguments.

Arguments are specified after the function name, inside the parentheses. You can add as many arguments as you want, just separate them with a comma.

The following example has a function with one argument (fname). When the function is called, we pass along a first name, which is used inside the function to print the full name:

**Arguments are often shortened to args in Python documentations.**

**Parameters or Arguments?**

The terms parameter and argument can be used for the same thing: information that are passed into a function.

**From a function's perspective:**

A parameter is the variable listed inside the parentheses in the function definition.

An argument is the value that is sent to the function when it is called.

In [ ]:
def my_function(fname):
  print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")

#Number of Arguments
By default, a function must be called with the correct number of arguments. Meaning that if your function expects 2 arguments, you have to call the function with 2 arguments, not more, and not less.

In [ ]:
#This function expects 2 arguments, and gets 2 arguments:

def my_function(fname, lname):
  print(fname + " " + lname)

my_function("Emil", "Refsnes")

#If you try to call the function with 1 or 3 arguments, you will get an error:
#This function expects 2 arguments, but gets only 1:

def my_function(fname, lname):
  print(fname + " " + lname)

my_function("Emil")

#Arbitrary Arguments, *args
If you do not know how many arguments that will be passed into your function, add a * before the parameter name in the function definition.

 **Arbitrary Arguments are often shortened to *args in Python documentations.**

This way the function will receive a tuple of arguments, and can access the items accordingly:

In [ ]:
#If the number of arguments is unknown, add a * before the parameter name:

def my_function(*kids):
  print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")

The youngest child is Linus

#Keyword Arguments
You can also send arguments with the key = value syntax.

This way the order of the arguments does not matter.

**The phrase Keyword Arguments are often shortened to kwargs in Python documentations.**

In [ ]:
def my_function(child3, child2, child1):
  print("The youngest child is " + child3)

my_function(child1 = "Emil", child2 = "Tobias", child3 = "Linus")

#Arbitrary Keyword Arguments, **kwargs
If you do not know how many keyword arguments that will be passed into your function, add two asterisk: ** before the parameter name in the function definition.

This way the function will receive a dictionary of arguments, and can access the items accordingly:


**Arbitrary Kword Arguments are often shortened to kwargs in Python documentations.**

In [ ]:
#If the number of keyword arguments is unknown, add a double ** before the parameter name:

def my_function(**kid):
  print("His last name is " + kid["lname"])

my_function(fname = "Tobias", lname = "Refsnes")

#Default Parameter Value
The following example shows how to use a default parameter value.

If we call the function without argument, it uses the default value:

In [ ]:
def my_function(country = "Norway"):
  print("I am from " + country)

my_function("Sweden")
my_function("India")
my_function()
my_function("Brazil")

#Passing a List as an Argument
You can send any data types of argument to a function (string, number, list, dictionary etc.), and it will be treated as the same data type inside the function.

E.g. if you send a List as an argument, it will still be a List when it reaches the function:

In [ ]:
def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)

#Return Values
To let a function return a value, use the return statement:

In [ ]:
def my_function(x):
  return 5 * x

print(my_function(3))
print(my_function(5))
print(my_function(9))

#The pass Statement
function definitions cannot be empty, but if you for some reason have a function definition with no content, put in the pass statement to avoid getting an error.

In [ ]:
def myfunction():
  pass

#Recursion
Python also accepts function recursion, which means a defined function can call itself.

Recursion is a common mathematical and programming concept. It means that a function calls itself. This has the benefit of meaning that you can loop through data to reach a result.

In [ ]:
def factorial(x):
    """This is a recursive function
    to find the factorial of an integer"""

    if x == 1:
        return 1
    else:
        return (x * factorial(x-1))


num = 3
print("The factorial of", num, "is", factorial(num))

The factorial of 3 is 6

#Python Lambda
A lambda function is a small anonymous function.

A lambda function can take any number of arguments, but can only have one expression.

#Syntax
lambda arguments : expression

The expression is executed and the result is returned:

In [ ]:
x = lambda a : a + 10
print(x(5))

#Lambda functions can take any number of arguments:
#Multiply argument a with argument b and return the result:

x = lambda a, b : a * b
print(x(5, 6))

#Summarize argument a, b, and c and return the result:

x = lambda a, b, c : a + b + c
print(x(5, 6, 2))

15
30
13

#Why Use Lambda Functions?
The power of lambda is better shown when you use them as an anonymous function inside another function.

Say you have a function definition that takes one argument, and that argument will be multiplied with an unknown number:

**Use lambda functions when an anonymous function is required for a short period of time.**

In [ ]:
#Use that function definition to make a function that always doubles the number you send in:
def myfunc(n): # Defines a function that takes 'n' as an argument
  return lambda a : a * n # Returns a lambda function that multiplies 'a' by 'n'

mydoubler = myfunc(2) # Calls myfunc(2), returning a lambda function that multiplies by 2

print(mydoubler(11)) # Calls the lambda function with a=11 → Output: 11 * 2 = 22

#Or, use the same function definition to make a function that always triples the number you send in:

def myfunc(n):
  return lambda a : a * n

mytripler = myfunc(3)

print(mytripler(11))

#Or, use the same function definition to make both functions, in the same program:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)
mytripler = myfunc(3)

print(mydoubler(11))
print(mytripler(11))

22
33
22
33

#Lambda functions within map():
Lambda functions are functions that do have any name. These functions are often supplied as parameters to other functions. Now let us try to embed lambda functions within the map() function. Consider the following example:

In [ ]:
tup= (5, 7, 22, 97, 54, 62, 77, 23, 73, 61)
newtuple = tuple(map(lambda x: x+3 , tup))
print(newtuple)

(8, 10, 25, 100, 57, 65, 80, 26, 76, 64)

#The filter() function:
The filter() function is used to create an output list consisting of values for which the function returns true. The syntax of it is as follows:

#SYNTAX:

filter(function, iterables)

Just like map(), this function can be used can also take user-defined functions as well as lambda functions as a parameter.

In [ ]:
def func(x):
    if x>=3:
        return x
y = filter(func, (1,2,3,4))
print(y)
print(list(y))

<filter object at 0x7ae05e456b30>
[3, 4]

#Using lambda within filter():

The lambda function that is used as a parameter actually defines the condition that is to be checked. For example:

In [ ]:
y = filter(lambda x: (x>=3), (1,2,3,4))
print(list(y))

[3, 4]

#The reduce() function:
The reduce() function, as the name describes, applies a given function to the iterables and returns a single value.
#SYNTAX:

reduce(function, iterables)

The function here defines what expression needs to be applied to the iterables. This function needs to be imported from the functools module. For Example:

In [ ]:
from functools import reduce
reduce(lambda a,b: a+b,[1,3,45])

49

#Using map(),filter() and reduce() functions along with each other:
When you do this, the internal functions are first solved and then the outer functions operate on the output of the internal functions.

Let us first try passing the filter() function as a parameter to the map() function.

#Using filter() within map():
The code given below first checks for the condition (x>=3) to be true for the iterables. Then, the output is mapped using the map() function.

If you filter out integers greater than or equal to 3 from the given tuple, you get [3,4] as the result. Then if you map this using(x+x) condition, you will get [6,8], which is the output.

In [ ]:
c = map(lambda x:x+x,filter(lambda x: (x>=3), (1,2,3,4)))
print(list(c))

[6, 8]

#Using map() within filter():

When you use the map() function within filter() function, the iterables are first operated upon by the map function and then the condition of filter() is applied to them.

In [ ]:
c = filter(lambda x: (x>=3),map(lambda x:x+x, (1,2,3,4)))  #lambda x: (x>=3)
print(list(c))

[4, 6, 8]

#Using map() and filter() within reduce():
The output of the internal functions is reduced according to the condition supplied to the reduce() function.

In [ ]:
from functools import reduce
d = reduce(lambda x,y: x+y,map(lambda x:x+x,filter(lambda x: (x>=3), (1,2,3,4))))
print(d)

14

<font color="red">Note: Python does not have built-in support for Arrays, but Python Lists can be used instead.</font>

#Arrays

<font color="red">Note: This page shows you how to use LISTS as ARRAYS, however, to work with arrays in Python you will have to import a library, like the NumPy library.</font>

Arrays are used to store multiple values in one single variable:

#What is an Array?
An array is a special variable, which can hold more than one value at a time.

If you have a list of items (a list of car names, for example), storing the cars in single variables could look like this:

car1 = "Ford"

car2 = "Volvo"

car3 = "BMW"

However, what if you want to loop through the cars and find a specific one? And what if you had not 3 cars, but 300?

The solution is an array!

An array can hold many values under a single name, and you can access the values by referring to an index number.

In [ ]:
cars = ["Ford", "Volvo", "BMW"]

#Get the value of the first array item:

x = cars[0]

#Modify the value of the first array item:

cars[0] = "Toyota"

#Use the len() method to return the length of an array (the number of elements in an array). Return the number of elements in the cars array:
x = len(cars)

#You can use the for in loop to loop through all the elements of an array.
for x in cars:
  print(x)

#You can use the append() method to add an element to an array.
cars.append("Honda")

#You can use the pop() method to remove an element from the array.
cars.pop(1)

#You can also use the remove() method to remove an element from the array.
cars.remove("Volvo")

#Array Methods
Python has a set of built-in methods that you can use on lists/arrays.

<table border="1">
  <tr>
    <th>Method</th>
    <th>Description</th>
  </tr>
  <tr>
    <td>append()</td>
    <td>Adds an element at the end of the list</td>
  </tr>
  <tr>
    <td>clear()</td>
    <td>Removes all the elements from the list</td>
  </tr>
  <tr>
    <td>copy()</td>
    <td>Returns a copy of the list</td>
  </tr>
  <tr>
    <td>count()</td>
    <td>Returns the number of elements with the specified value</td>
  </tr>
  <tr>
    <td>extend()</td>
    <td>Add the elements of a list (or any iterable), to the end of the current list</td>
  </tr>
  <tr>
    <td>index()</td>
    <td>Returns the index of the first element with the specified value</td>
  </tr>
  <tr>
    <td>insert()</td>
    <td>Adds an element at the specified position</td>
  </tr>
  <tr>
    <td>pop()</td>
    <td>Removes the element at the specified position</td>
  </tr>
  <tr>
    <td>remove()</td>
    <td>Removes the first item with the specified value</td>
  </tr>
  <tr>
    <td>reverse()</td>
    <td>Reverses the order of the list</td>
  </tr>
  <tr>
    <td>sort()</td>
    <td>Sorts the list</td>
  </tr>
</table>

#Python Classes/Objects
Python is an object oriented programming language.

Almost everything in Python is an object, with its properties and methods.

A Class is like an object constructor, or a "blueprint" for creating objects.

#Create a Class
To create a class, use the keyword class:

In [ ]:
#Create a class named MyClass, with a property named x:

class MyClass:
  x = 5

#Create Object
Now we can use the class named MyClass to create objects:

In [ ]:
#Create an object named p1, and print the value of x:
class MyClass:
  x = 5

p1 = MyClass()
print(p1.x)

5

#The __init__() Function
The examples above are classes and objects in their simplest form, and are not really useful in real life applications.

To understand the meaning of classes we have to understand the built-in __init__() function.

All classes have a function called __init__(), which is always executed when the class is being initiated.

Use the __init__() function to assign values to object properties, or other operations that are necessary to do when the object is being created:

<font color="red">Note: The __init__() function is called automatically every time the class is being used to create a new object.</font>

In [ ]:
#Create a class named Person, use the __init__() function to assign values for name and age:

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

John
36

#The __str__() Function
https://www.datacamp.com/tutorial/f-string-formatting-in-python

The __str__() function controls what should be returned when the class object is represented as a string.

If the __str__() function is not set, the string representation of the object is returned:

In [ ]:
#The string representation of an object WITHOUT the __str__() function:

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1)

#The string representation of an object WITH the __str__() function:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def __str__(self):
    return f"{self.name}({self.age})"

p1 = Person("John", 36)

print(p1)

<__main__.Person object at 0x7e344a96abc0>
John(36)

In [ ]:
class Sample:

    def __init__(self, name, age):
        self.name = name
        self.age = age

    ## this method will be called when we print the object
    def __str__(self):
        return f'{self.name} is {self.age} years old.'

s1=Sample("John",36)
print(s1)

John is 36 years old.

#Object Methods
Objects can also contain methods. Methods in objects are functions that belong to the object.

Let us create a method in the Person class:

<font color="red"> Note: The self parameter is a reference to the current instance of the class, and is used to access variables that belong to the class.</font>

In [ ]:
#Insert a function that prints a greeting, and execute it on the p1 object:

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def myfunc(self):
    print("Hello my name is " + self.name)

p1 = Person("John", 36)
p1.myfunc()

Hello my name is John

In [ ]:
#The self Parameter
The self parameter is a reference to the current instance of the class, and is used to access variables that belongs to the class.

It does not have to be named self , you can call it whatever you like, but it has to be the first parameter of any function in the class:

In [ ]:
#Use the words mysillyobject and abc instead of self:

class Person:
  def __init__(mysillyobject, name, age):
    mysillyobject.name = name
    mysillyobject.age = age

  def myfunc(abc):
    print("Hello my name is " + abc.name)

p1 = Person("John", 36)
p1.myfunc()

Hello my name is John

#Modify Object Properties
You can modify properties on objects like this:

#Delete Object Properties
You can delete properties on objects by using the del keyword:

#The pass Statement
class definitions cannot be empty, but if you for some reason have a class definition with no content, put in the pass statement to avoid getting an error.

In [ ]:
#Delete the age property from the p1 object:

del p1.age

#Delete the p1 object:

del p1

class Person:
  pass

#Python Inheritance
Inheritance allows us to define a class that inherits all the methods and properties from another class.

Parent class is the class being inherited from, also called base class.

Child class is the class that inherits from another class, also called derived class.

##Create a Parent Class
Any class can be a parent class, so the syntax is the same as creating any other class:

In [ ]:
#Create a class named Person, with firstname and lastname properties, and a printname method:

class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

#Use the Person class to create an object, and then execute the printname method:

x = Person("John", "Doe")
x.printname()

##Create a Child Class
To create a class that inherits the functionality from another class, send the parent class as a parameter when creating the child class:

<font color= "red">Note: Use the pass keyword when you do not want to add any other properties or methods to the class.</font>

In [ ]:
#Create a class named Student, which will inherit the properties and methods from the Person class:

class Student(Person):
  pass

#Use the Student class to create an object, and then execute the printname method:

x = Student("Mike", "Olsen")
x.printname()

Mike Olsen

##Add the __init__() Function
So far we have created a child class that inherits the properties and methods from its parent.

We want to add the __init__() function to the child class (instead of the pass keyword).

<font color= "red">Note: The __init__() function is called automatically every time the class is being used to create a new object.</font>

When you add the __init__() function, the child class will no longer inherit the parent's __init__() function.

<font color= "red">Note: The child's __init__() function overrides the inheritance of the parent's __init__() function.</font>

To keep the inheritance of the parent's __init__() function, add a call to the parent's __init__() function:

In [ ]:
#Add the __init__() function to the Student class:

class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname):
    #add properties etc.
    Person.__init__(self, fname, lname)
x = Student("Mike", "Olsen")
x.printname()

Mike Olsen

In [ ]:
class Student(Person):
  def __init__(self, fname, lname):
    Person.__init__(self, fname, lname)

#Use the super() Function
Python also has a super() function that will make the child class inherit all the methods and properties from its parent:

In [ ]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname):
    super().__init__(fname, lname)

#By using the super() function, you do not have to use the name of the parent element, it will automatically inherit the methods and properties from its parent.

#Add Properties
#Add a property called graduationyear to the Student class:

class Student(Person):
  def __init__(self, fname, lname):
    super().__init__(fname, lname)
    self.graduationyear = 2019



#In the example below, the year 2019 should be a variable, and passed into the Student class when creating student objects. To do so, add another parameter in the __init__() function:
#Add a year parameter, and pass the correct year when creating objects:

class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname)
    self.graduationyear = year

x = Student("Mike", "Olsen", 2019)

#Add Methods

In [ ]:
#Add a method called welcome to the Student class:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname)
    self.graduationyear = year

  def welcome(self):
    print("Welcome", self.firstname, self.lastname, "to the class of", self.graduationyear)

x = Student("Mike", "Olsen", 2019)
x.welcome()

Welcome Mike Olsen to the class of 2019

#Python Iterators
An iterator is an object that contains a countable number of values.

An iterator is an object that can be iterated upon, meaning that you can traverse through all the values.

Technically, in Python, an iterator is an object which implements the iterator protocol, which consist of the methods __iter__() and __next__().

##Iterator vs Iterable
An iterable is any object that can be looped over, and an iterator is an object that keeps track of the current state during iteration and provides the next value when requested. Every iterator is an iterable, but not every iterable is an iterator.

Lists, tuples, dictionaries, and sets are all iterable objects. They are iterable containers which you can get an iterator from.

All these objects have a iter() method which is used to get an iterator:

In [ ]:
#We can also use a for loop to iterate through an iterable object:

#Iterate the values of a tuple:

mytuple = ("apple", "banana", "cherry")

for x in mytuple:
  print(x)

#Iterate the characters of a string:

mystr = "banana"

for x in mystr:
  print(x)

#Return an iterator from a tuple, and print each value:

mytuple = ("apple", "banana", "cherry")
myit = iter(mytuple)

print(next(myit))
print(next(myit))
print(next(myit))

#strings are also iterable objects, containing a sequence of characters:

mystr = "banana"
myit = iter(mystr)

print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))

apple
banana
cherry
b
a
n
a
n
a
apple
banana
cherry
b
a
n
a
n
a

In [ ]:
my_list = [1, 2, 3]
iterator = iter(my_list)  # Get an iterator from the iterable
print(iterator)

my_iter = iter(my_list)
print(next(my_iter))
print(next(my_iter))

<list_iterator object at 0x7e45c3104100>
1
2

In [ ]:
print(next(my_iter))

3

In [ ]:
print(next(my_iter))

StopIteration:

#Create an Iterator
To create an object/class as an iterator you have to implement the methods __iter__() and __next__() to your object.

As you have learned in the Python Classes/Objects chapter, all classes have a function called __init__(), which allows you to do some initializing when the object is being created.

The __iter__() method acts similar, you can do operations (initializing etc.), but must always return the iterator object itself.

The __next__() method also allows you to do operations, and must return the next item in the sequence.

In [ ]:
#Create an iterator that returns numbers, starting with 1, and each sequence will increase by one (returning 1,2,3,4,5 etc.):

class MyNumbers:
  def __iter__(self):
    self.a = 1
    return self

  def __next__(self):
    x = self.a
    self.a += 1
    return x

myclass = MyNumbers()
myiter = iter(myclass)

print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))

1
2
3
4
5

#StopIteration
The example above would continue forever if you had enough next() statements, or if it was used in a for loop.

To prevent the iteration from going on forever, we can use the StopIteration statement.

In the __next__() method, we can add a terminating condition to raise an error if the iteration is done a specified number of times:

In [ ]:
class MyNumbers:
  def __iter__(self):
    self.a = 1
    return self

  def __next__(self):
    if self.a <= 20:
      x = self.a
      self.a += 1
      return x
    else:
      raise StopIteration

myclass = MyNumbers()
myiter = iter(myclass)

for x in myiter:
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

#Python Polymorphism
The word "polymorphism" means "many forms", and in programming it refers to methods/functions/operators with the same name that can be executed on many objects or classes.

##Function Polymorphism
An example of a Python function that can be used on different objects is the len() function.

##String
For strings len() returns the number of characters:

In [ ]:
x = "Hello World!"

print(len(x))

12

#Tuple
For tuples len() returns the number of items in the tuple:

In [ ]:
mytuple = ("apple", "banana", "cherry")

print(len(mytuple))

3

#Dictionary
For dictionaries len() returns the number of key/value pairs in the dictionary:

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

print(len(thisdict))

3

#Class Polymorphism
Polymorphism is often used in Class methods, where we can have multiple classes with the same method name.

For example, say we have three classes: Car, Boat, and Plane, and they all have a method called move():

class Car:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Drive!")

class Boat:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Sail!")

class Plane:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Fly!")

car1 = Car("Ford", "Mustang")       #Create a Car class
boat1 = Boat("Ibiza", "Touring 20") #Create a Boat class
plane1 = Plane("Boeing", "747")     #Create a Plane class

for x in (car1, boat1, plane1):
  x.move()

In [ ]:
class Car:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Drive!")

class Boat:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Sail!")

class Plane:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Fly!")

car1 = Car("Ford", "Mustang")       #Create a Car class
boat1 = Boat("Ibiza", "Touring 20") #Create a Boat class
plane1 = Plane("Boeing", "747")     #Create a Plane class

for x in (car1, boat1, plane1):
  x.move()

Drive!
Sail!
Fly!

#Inheritance Class Polymorphism
What about classes with child classes with the same name? Can we use polymorphism there?

Yes. If we use the example above and make a parent class called Vehicle, and make Car, Boat, Plane child classes of Vehicle, the child classes inherits the Vehicle methods, but can override them:

In [ ]:
class Vehicle:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Move!")

class Car(Vehicle):
  pass

class Boat(Vehicle):
  def move(self):
    print("Sail!")

class Plane(Vehicle):
  def move(self):
    print("Fly!")

car1 = Car("Ford", "Mustang") #Create a Car object
boat1 = Boat("Ibiza", "Touring 20") #Create a Boat object
plane1 = Plane("Boeing", "747") #Create a Plane object

for x in (car1, boat1, plane1):
  print(x.brand)
  print(x.model)
  x.move()

Ford
Mustang
Move!
Ibiza
Touring 20
Sail!
Boeing
747
Fly!

Child classes inherits the properties and methods from the parent class.

In the example above you can see that the Car class is empty, but it inherits brand, model, and move() from Vehicle.

The Boat and Plane classes also inherit brand, model, and move() from Vehicle, but they both override the move() method.

Because of polymorphism we can execute the same method for all classes.

#Python Scope
A variable is only available from inside the region it is created. This is called scope.
#Local Scope
A variable created inside a function belongs to the local scope of that function, and can only be used inside that function.

In [ ]:
#A variable created inside a function is available inside that function:

def myfunc():
  x = 300
  print(x)

myfunc()

300

#Function Inside Function
As explained in the example above, the variable x is not available outside the function, but it is available for any function inside the function:

In [ ]:
#The local variable can be accessed from a function within the function:

def myfunc():
  x = 300
  def myinnerfunc():
    print(x)
  myinnerfunc()

myfunc()

300

#Global Scope
A variable created in the main body of the Python code is a global variable and belongs to the global scope.

Global variables are available from within any scope, global and local.

In [ ]:
#A variable created outside of a function is global and can be used by anyone:

x = 300

def myfunc():
  print(x)

myfunc()

print(x)

300
300

#Naming Variables
If you operate with the same variable name inside and outside of a function, Python will treat them as two separate variables, one available in the global scope (outside the function) and one available in the local scope (inside the function):

In [ ]:
#The function will print the local x, and then the code will print the global x:

x = 300

def myfunc():
  x = 200
  print(x)

myfunc()

print(x)

200
300

#Global Keyword
If you need to create a global variable, but are stuck in the local scope, you can use the global keyword.

The global keyword makes the variable global.

In [ ]:
#If you use the global keyword, the variable belongs to the global scope:

def myfunc():
  global x
  x = 300

myfunc()

print(x)

#Also, use the global keyword if you want to make a change to a global variable inside a function.

#To change the value of a global variable inside a function, refer to the variable by using the global keyword:

x = 300

def myfunc():
  global x
  x = 200

myfunc()

print(x)

300
200

#Python Modules
##What is a Module?
Consider a module to be the same as a code library.

A file containing a set of functions you want to include in your application.

##Create a Module
To create a module just save the code you want in a file with the file extension .py:

In [ ]:
#Save this code in a file named mymodule.py

def greeting(name):
  print("Hello, " + name)

##Use a Module
Now we can use the module we just created, by using the import statement:

<font color="red">Note: When using a function from a module, use the syntax: module_name.function_name.</font>

In [ ]:
#Import the module named mymodule, and call the greeting function:

import mymodule

mymodule.greeting("Jonathan")

ModuleNotFoundError: No module named 'mymodule'

#Variables in Module
The module can contain functions, as already described, but also variables of all types (arrays, dictionaries, objects etc):

In [ ]:
#Save this code in the file mymodule.py

person1 = {
  "name": "John",
  "age": 36,
  "country": "Norway"
}

#Import the module named mymodule, and access the person1 dictionary:

import mymodule

a = mymodule.person1["age"]
print(a)

##Naming a Module
You can name the module file whatever you like, but it must have the file extension .py

##Re-naming a Module
You can create an alias when you import a module, by using the as keyword:

In [ ]:
#Create an alias for mymodule called mx:

import mymodule as mx

a = mx.person1["age"]
print(a)

#Built-in Modules
There are several built-in modules in Python, which you can import whenever you like.

In [ ]:
#Import and use the platform module:

import platform

x = platform.system()
print(x)

Linux

#Using the dir() Function
There is a built-in function to list all the function names (or variable names) in a module. The dir() function:

<font color="red">Note: The dir() function can be used on all modules, also the ones you create yourself.</font>

In [ ]:
#List all the defined names belonging to the platform module:

import platform

x = dir(platform)
print(x)

['_Processor', '_WIN32_CLIENT_RELEASES', '_WIN32_SERVER_RELEASES', '__builtins__', '__cached__', '__copyright__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_comparable_version', '_component_re', '_default_architecture', '_follow_symlinks', '_get_machine_win32', '_ironpython26_sys_version_parser', '_ironpython_sys_version_parser', '_java_getprop', '_libc_search', '_mac_ver_xml', '_node', '_norm_version', '_os_release_cache', '_os_release_candidates', '_os_release_line', '_os_release_unescape', '_parse_os_release', '_platform', '_platform_cache', '_pypy_sys_version_parser', '_sys_version', '_sys_version_cache', '_sys_version_parser', '_syscmd_file', '_syscmd_ver', '_uname_cache', '_unknown_as_blank', '_ver_output', '_ver_stages', 'architecture', 'collections', 'freedesktop_os_release', 'functools', 'itertools', 'java_ver', 'libc_ver', 'mac_ver', 'machine', 'node', 'os', 'platform', 'processor', 'python_branch', 'python_build', 'python_compiler', 'python_implementation', 'python_revision', 'python_version', 'python_version_tuple', 're', 'release', 'subprocess', 'sys', 'system', 'system_alias', 'uname', 'uname_result', 'version', 'win32_edition', 'win32_is_iot', 'win32_ver']

#Import From Module
You can choose to import only parts from a module, by using the from keyword.

<font color="red">Note: When importing using the from keyword, do not use the module name when referring to elements in the module. Example: person1["age"], not mymodule.person1["age"]</font>

In [ ]:
#The module named mymodule has one function and one dictionary:

def greeting(name):
  print("Hello, " + name)

person1 = {
  "name": "John",
  "age": 36,
  "country": "Norway"
}

In [ ]:
#Import only the person1 dictionary from the module:

from mymodule import person1

print (person1["age"])

#Python Datetime
##Python Dates
A date in Python is not a data type of its own, but we can import a module named datetime to work with dates as date objects.

In [ ]:
#Import the datetime module and display the current date:

import datetime

x = datetime.datetime.now() #the first usage datetime.datetime is used to access
                            #the datetime class within the datetime module.
print(x)

2024-02-15 04:32:34.348413

#Date Output
When we execute the code from the example above the result will be:

2023-12-19 11:16:00.222109
The date contains year, month, day, hour, minute, second, and microsecond.

The datetime module has many methods to return information about the date object.

Here are a few examples, you will learn more about them later in this chapter:

In [ ]:
#Return the year and name of weekday:

import datetime

x = datetime.datetime.now()

print(x.year)
print(x.strftime("%A")) #strftime: string format time method..strftime() is a method in Python's
                        #datetime class that is used to format datetime objects as strings.

2024
Thursday

#Creating Date Objects
To create a date, we can use the datetime() class (constructor) of the datetime module.

The datetime() class requires three parameters to create a date: year, month, day.

The datetime() class also takes parameters for time and timezone (hour, minute, second, microsecond, tzone), but they are optional, and has a default value of 0, (None for timezone).

#The strftime() Method
The datetime object has a method for formatting date objects into readable strings.

The method is called strftime(), and takes one parameter, format, to specify the format of the returned string:

In [ ]:
#Create a date object:

import datetime

x = datetime.datetime(2020, 5, 17)

print(x)

#Display the name of the month:

formatted_date = x.strftime("%Y/%m/%d")
print(formatted_date)

2020-05-17 00:00:00
2020/05/17

In [ ]:
#import datetime

x = datetime.datetime(2018, 6, 1)

print(x.strftime("%B"))

June

#A reference of all the legal format codes:

<table class="ws-table-all notranslate">
<tbody><tr>
<th style="width:25%">Directive</th>
<th style="width:35%">Description</th>
<th style="width:30%">Example</th>
</tr>
<tr>
<td>%a</td>
<td>Weekday, short version</td>
<td>Wed</td>

</tr>
<tr>
<td>%A</td>
<td>Weekday, full version</td>
<td>Wednesday</td>

</tr>
<tr>
<td>%w</td>
<td>Weekday as a number 0-6, 0 is Sunday</td>
<td>3</td>

</tr>
<tr>
<td>%d</td>
<td>Day of month 01-31</td>
<td>31</td>

</tr>
<tr>
<td>%b</td>
<td>Month name, short version</td>
<td>Dec</td>

</tr>
<tr>
<td>%B</td>
<td>Month name, full version</td>
<td>December</td>

</tr>
<tr>
<td>%m</td>
<td>Month as a number 01-12</td>
<td>12</td>

</tr>
<tr>
<td>%y</td>
<td>Year, short version, without century</td>
<td>18</td>

</tr>
<tr>
<td>%Y</td>
<td>Year, full version</td>
<td>2018</td>

</tr>
<tr>
<td>%H</td>
<td>Hour 00-23</td>
<td>17</td>

</tr>
<tr>
<td>%I</td>
<td>Hour 00-12</td>
<td>05</td>

</tr>
<tr>
<td>%p</td>
<td>AM/PM</td>
<td>PM</td>

</tr>
<tr>
<td>%M</td>
<td>Minute 00-59</td>
<td>41</td>

</tr>
<tr>
<td>%S</td>
<td>Second 00-59</td>
<td>08</td>

</tr>
<tr>
<td>%f</td>
<td>Microsecond 000000-999999</td>
<td>548513</td>

</tr>
<tr>
<td>%z</td>
<td>UTC offset</td>
<td>+0100</td>
<td></td>
</tr>
<tr>
<td>%Z</td>
<td>Timezone</td>
<td>CST</td>
<td></td>
</tr>
<tr>
<td>%j</td>
<td>Day number of year 001-366</td>
<td>365</td>

</tr>
<tr>
<td>%U</td>
<td>Week number of year, Sunday as the first day of week, 00-53</td>
<td>52</td>

</tr>
<tr>
<td>%W</td>
<td>Week number of year, Monday as the first day of week, 00-53</td>
<td>52</td>

</tr>
<tr>
<td>%c</td>
<td>Local version of date and time</td>
<td>Mon Dec 31 17:41:00 2018</td>

</tr>
<tr>
<td>%C</td>
<td>Century</td>
<td>20</td>

</tr>
<tr>
<td>%x</td>
<td>Local version of date</td>
<td>12/31/18</td>

</tr>
<tr>
<td>%X</td>
<td>Local version of time</td>
<td>17:41:00</td>

</tr>
<tr>
<td>%%</td>
<td>A % character</td>
<td>%</td>

</tr>
<tr>
<td>%G</td>
<td>ISO 8601 year</td>
<td>2018</td>

</tr>
<tr>
<td>%u</td>
<td>ISO 8601 weekday (1-7)</td>
<td>1</td>

</tr>
<tr>
<td>%V</td>
<td>ISO 8601 weeknumber (01-53)</td>
<td>01</td>

</tr>
</tbody></table>

#Python Math
Python has a set of built-in math functions, including an extensive math module, that allows you to perform mathematical tasks on numbers.

#Built-in Math Functions
The min() and max() functions can be used to find the lowest or highest value in an iterable:

In [ ]:
x = min(5, 10, 25)
y = max(5, 10, 25)

print(x)
print(y)

#The abs() function returns the absolute (positive) value of the specified number:
x = abs(-7.25)

print(x)

#The pow(x, y) function returns the value of x to the power of y (xy).
#Return the value of 4 to the power of 3 (same as 4 * 4 * 4):

x = pow(4, 3)

print(x)

5
25
7.25
64

#The Math Module
Python has also a built-in module called math, which extends the list of mathematical functions.

To use it, you must import the math module:

When you have imported the math module, you can start using methods and constants of the module.

The math.sqrt() method for example, returns the square root of a number:

In [ ]:
import math

x = math.sqrt(64)

print(x)

#The math.ceil() method rounds a number upwards to its nearest integer, and the math.floor() method rounds a number downwards to its nearest integer, and returns the result:

x = math.ceil(1.4)
y = math.floor(1.4)

print(x) # returns 2
print(y) # returns 1

#The math.pi constant, returns the value of PI (3.14...):

x = math.pi

print(x)

8.0
2
1
3.141592653589793

#Sys Module in Python

https://www.tutorialspoint.com/what-is-python-s-sys-module

https://www.geeksforgeeks.org/python-sys-module/

Python sys.version

In this example, sys.version is used which returns a string containing the version of Python Interpreter with some additional information. This shows how the sys module interacts with the interpreter. Let us dive into the article to get more information about the sys module.

In [ ]:
import sys
print(sys.version)

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

#Input and Output using Python Sys
The sys modules provide variables for better control over input or output. We can even redirect the input and output to other devices. This can be done using three variables –

<ul>
<li value="1"><span>stdin</span></li>
<li value="2"><span>stdout</span></li>
<li value="3"><span>stderr</span></li>
</ul>

##Read from stdin in Python
stdin: It can be used to get input from the command line directly. It is used for standard input. It internally calls the input() method. It, also, automatically adds ‘\n’ after each sentence.

##Example:

This code reads lines from the standard input until the user enters ‘q’. For each line, it prints “Input : ” followed by the line. Finally, it prints “Exit”.

In [ ]:
import sys
for line in sys.stdin:
    if 'q' == line.rstrip():
        break
    print(f'Input : {line}')

print("Exit")

Exit

#Python sys.stdout Method
stdout: A built-in file object that is analogous to the interpreter’s standard output stream in Python. stdout is used to display output directly to the screen console. Output can be of any form, it can be output from a print statement, an expression statement, and even a prompt direct for input. By default, streams are in text mode. In fact, wherever a print function is called within the code, it is first written to sys.stdout and then finally on to the screen.

##Example:

This code will print the string “Hello” to the standard output. The sys.stdout object represents the standard output stream, and the write() method writes the specified string to the stream.

In [ ]:
import sys
sys.stdout.write('Hello')

Hello

#stderr function in Python
stderr: Whenever an exception occurs in Python it is written to sys.stderr.

##Example:

This code will print the string “Hello World” to the standard error stream. The sys.stderr object represents the standard error stream, and the print() function writes the specified strings to the stream.

In [ ]:
import sys
def print_to_stderr(a):
    print(a, file = sys.stderr)

print_to_stderr("Hello World")

Hello World

#Command Line Arguments
Command-line arguments are those which are passed during the calling of the program along with the calling statement. To achieve this using the sys module, the sys module provides a variable called sys.argv. It’s main purpose are:

It is a list of command-line arguments.
len(sys.argv) provides the number of command-line arguments.
sys.argv[0] is the name of the current Python script.
Example: Consider a program for adding numbers and the numbers are passed along with the calling statement.

This code calculates the sum of the command-line arguments passed to the Python script. It imports the sys module to access the command-line arguments and then iterates over the arguments, converting each one to an integer and adding it to a running total. Finally, it prints the total sum of the arguments.

In [ ]:
import sys
n = len(sys.argv)
print("Total arguments passed:", n)
print("\nName of Python script:", sys.argv[0])

for i in range(1, n):
    print(sys.argv[i], end = " ")
Sum = 0
for i in range(1, n):
    Sum += int(sys.argv[i])

print("\n\nResult:", Sum)

#Exiting the Program
sys.exit([arg]) can be used to exit the program. The optional argument arg can be an integer giving the exit or another type of object. If it is an integer, zero is considered “successful termination”.

Note: A string can also be passed to the sys.exit() method.

Example:

This code checks if the age is less than 18. If it is, it exits the program with a message “Age less than 18”. Otherwise, it prints the message “Age is not less than 18”. The sys.exit() function takes an optional message as an argument, which is displayed when the program exits.

In [ ]:
import sys
age = 17
if age < 18:
    sys.exit("Age less than 18")
else:
    print("Age is not less than 18")

SystemExit: Age less than 18

/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [ ]:
for i in range(1,5):
    if i == 4:
        sys.exit("number is 4 so exiting")
    print(i*5)

5
10
15

SystemExit: number is 4 so exiting

#Working with Modules
sys.path is a built-in variable within the sys module that returns the list of directories that the interpreter will search for the required module.

When a module is imported within a Python file, the interpreter first searches for the specified module among its built-in modules. If not found it looks through the list of directories defined by sys.path.

**Note: sys.path is an ordinary list and can be manipulated**

Example 1: Listing out all the paths

This code will print the system paths that Python uses to search for modules. The sys.path list contains the directories that Python will search for modules when it imports them.

In [ ]:
import sys
print(sys.path)

['/content', '/env/python', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.10/dist-packages/IPython/extensions', '/root/.ipython']

#Reference Count
In Python, the reference count refers to the number of references or pointers pointing to a specific object in memory. Python uses automatic memory management through a technique called garbage collection, and the reference count is a crucial part of this process.

Every object in Python has a reference count, which is initially set to 1 when the object is created. When a new reference to the object is made (e.g., by assigning the object to a new variable), the reference count is incremented. When a reference is removed (e.g., by deleting a variable or reassigning it to a different object), the reference count is decremented. When the reference count of an object reaches 0, it means that there are no more references to that object, and the memory occupied by the object can be reclaimed by the garbage collector.

You can use the sys.getrefcount() function from the sys module to get the current reference count of an object. However, note that this function returns a count that is higher than the actual count due to the temporary reference created by the function itself.

Example:

This code prints the reference count of the object a. The reference count of an object is the number of times it is referenced by other objects. An object is garbage collected when its reference count reaches 0, meaning that it is no longer referenced by any other objects

In [ ]:
import sys
a = 'Geeks'
print(sys.getrefcount(a))

3

#Python Try Except
The try block lets you test a block of code for errors.

The except block lets you handle the error.

The else block lets you execute code when there is no error.

The finally block lets you execute code, regardless of the result of the try- and except blocks.

##Exception Handling
When an error occurs, or exception as we call it, Python will normally stop and generate an error message.

These exceptions can be handled using the try statement:

In [ ]:
#The try block will generate an exception, because x is not defined:

try:
  print(x)
except:
  print("An exception occurred")

#Many Exceptions
You can define as many exception blocks as you want, e.g. if you want to execute a special block of code for a special kind of error:

In [ ]:
#Print one message if the try block raises a NameError and another for other errors:

try:
  print(x)
except NameError:
  print("Variable x is not defined")
except:
  print("Something else went wrong")

#Else
You can use the else keyword to define a block of code to be executed if no errors were raised:

In [ ]:
#In this example, the try block does not generate any error:

try:
  print("Hello")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")

#Finally
The finally block, if specified, will be executed regardless if the try block raises an error or not.

In [ ]:
try:
  print(x)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")

In [ ]:
try:
  f = open("demofile.txt")
  try:
    f.write("Lorum Ipsum")
  except:
    print("Something went wrong when writing to the file")
  finally:
    f.close()
except:
  print("Something went wrong when opening the file")

#Raise an exception
As a Python developer you can choose to throw an exception if a condition occurs.

To throw (or raise) an exception, use the raise keyword.

The raise keyword is used to raise an exception.

You can define what kind of error to raise, and the text to print to the user.

In [ ]:
#Raise an error and stop the program if x is lower than 0:

x = -1

if x < 0:
  raise Exception("Sorry, no numbers below zero")

In [ ]:
#Raise a TypeError if x is not an integer:

x = "hello"

if not type(x) is int:
  raise TypeError("Only integers are allowed")

#Python File Open
File handling is an important part of any web application.

Python has several functions for creating, reading, updating, and deleting files.

##File Handling
The key function for working with files in Python is the open() function.

The open() function takes two parameters; filename, and mode.

There are four different methods (modes) for opening a file:

"r" - Read - Default value. Opens a file for reading, error if the file does not exist

"a" - Append - Opens a file for appending, creates the file if it does not exist

"w" - Write - Opens a file for writing, creates the file if it does not exist

"x" - Create - Creates the specified file, returns an error if the file exists

##In addition you can specify if the file should be handled as binary or text mode

"t" - Text - Default value. Text mode

"b" - Binary - Binary mode (e.g. images)

##Syntax
To open a file for reading it is enough to specify the name of the file:

Because "r" for read, and "t" for text are the default values, you do not need to specify them.

<font color= "red">Note: Make sure the file exists, or else you will get an error.</font>

In [ ]:
f = open("demofile.txt")
#The code above is the same as:

f = open("demofile.txt", "rt")

#Open a File on the Server
Assume we have the following file, located in the same folder as Python:

demofile.txt

Hello! Welcome to demofile.txt
This file is for testing purposes.
Good Luck!


To open the file, use the built-in open() function.

The open() function returns a file object, which has a read() method for reading the content of the file:

In [ ]:
f = open("demofile.txt", "r")
print(f.read())

#If the file is located in a different location, you will have to specify the file path, like this:

#Open a file on a different location:

f = open("D:\\myfiles\welcome.txt", "r")
print(f.read())

#Read Only Parts of the File
By default the read() method returns the whole text, but you can also specify how many characters you want to return:

In [ ]:
#Return the 5 first characters of the file:

f = open("demofile.txt", "r")
print(f.read(5))

#Read Lines
You can return one line by using the readline() method:
By calling readline() two times, you can read the two first lines:

<font color="red">Note: You should always close your files, in some cases, due to buffering, changes made to a file may not show until you close the file.</font>

In [ ]:
#Read one line of the file:

f = open("demofile.txt", "r")
print(f.readline())

f = open("demofile.txt", "r")
print(f.readline())
print(f.readline())


#By looping through the lines of the file, you can read the whole file, line by line:
f = open("demofile.txt", "r")
for x in f:
  print(x)


#It is a good practice to always close the file when you are done with it.
f = open("demofile.txt", "r")
print(f.readline())
f.close()

#Write to an Existing File
To write to an existing file, you must add a parameter to the open() function:

"a" - Append - will append to the end of the file

"w" - Write - will overwrite any existing content

<font color= "red">Note: the "w" method will overwrite the entire file.</font>

In [ ]:
#Open the file "demofile2.txt" and append content to the file:

f = open("demofile2.txt", "a")
f.write("Now the file has more content!")
f.close()

#open and read the file after the appending:
f = open("demofile2.txt", "r")
print(f.read())

In [ ]:
#Open the file "demofile3.txt" and overwrite the content:

f = open("demofile3.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()

#open and read the file after the overwriting:
f = open("demofile3.txt", "r")
print(f.read())

#Create a New File
To create a new file in Python, use the open() method, with one of the following parameters:

"x" - Create - will create a file, returns an error if the file exist

"a" - Append - will create a file if the specified file does not exist

"w" - Write - will create a file if the specified file does not exist

In [ ]:
#Create a file called "myfile.txt":

f = open("myfile.txt", "x")

#Create a new file if it does not exist:

f = open("myfile.txt", "w")

#Python Delete File
##Delete a File
To delete a file, you must import the OS module, and run its os.remove() function:

In [ ]:
#Remove the file "demofile.txt":

import os
os.remove("demofile.txt")

#Check if File exist:
To avoid getting an error, you might want to check if the file exists before you try to delete it:

In [ ]:
#Check if file exists, then delete it:

import os
if os.path.exists("demofile.txt"):
  os.remove("demofile.txt")
else:
  print("The file does not exist")

#Delete Folder
To delete an entire folder, use the os.rmdir() method:

<font color="red">Note: You can only remove empty folders.</font>

In [ ]:
#Remove the folder "myfolder":
import os
os.rmdir("myfolder")

# RegEx Module

https://www.programiz.com/python-programming/regex

A Regular Expression (RegEx) is a sequence of characters that defines a search pattern.

For example,

^a...s$

The above code defines a RegEx pattern. The pattern is: any five letter string starting with a and ending with s.

A pattern defined using RegEx can be used to match against a string.

Expression	  String	  Matched?
^a...s$	      abs	      No match
              alias	    Match

Python has a module named "re" to work with RegEx.

re.match() function to search pattern within the test_string. The method returns a match object if the search is successful. If not, it returns None.

In [2]:
#Explanation:
#^ → Start of the string
#a → The string must start with 'a'
#... → Any three characters (each dot . matches exactly one character)
#s → Followed by 's'
#$ → End of the string

import re

pattern = '^a...s$'
test_string = 'adbgs'
test_string1 = 'adbs'
result = re.match(pattern, test_string1)

if result:
  print("Search successful.")
else:
  print("Search unsuccessful.")

Search unsuccessful.

re.findall()

The re.findall() method returns a list of strings containing all matches. If the pattern is not found, re.findall() returns an empty list.

It returns all non-overlapping matches of the entire pattern

If the pattern has capturing groups (like (a|b|c)), it returns only the part captured (i.e. 'a', 'b', or 'c'), not the full match

In [3]:
# Program to extract numbers from a string

import re

string = 'axz bxz'
pattern = '(a|b|c)xz'
pattern1='[abc]xz'
result = re.findall(pattern1, string)
print(result)
result = re.findall(pattern, string)
print(result)

['axz', 'bxz']
['a', 'b']

In [ ]:
# Program to extract numbers from a string

import re

string = 'hello 12 hi 89. Howdy 34'
pattern = '\d+'

result = re.findall(pattern, string)
print(result)

# Output: ['12', '89', '34']

re.split()

The re.split method splits the string where there is a match and returns a list of strings where the splits have occurred.

If the pattern is not found, re.split() returns a list containing the original string.

In [ ]:
import re

string = 'Twelve:1 Eighty nine:89.'
pattern = '\d+'

result = re.split(pattern, string)
print(result)

# Output: ['Twelve:', ' Eighty nine:', '.']

['Twelve:', ' Eighty nine:', '.']

In [ ]:
#You can pass maxsplit argument to the re.split() method. It's the maximum number of splits that will occur.
#By the way, the default value of maxsplit is 0; meaning all possible splits.

import re

string = 'Twelve:12 Eighty nine:89 Nine:9.'
pattern = '\d+'

# maxsplit = 1
# split only at the first occurrence
result = re.split(pattern, string, 2)
print(result)

# Output: ['Twelve:', ' Eighty nine:89 Nine:9.']

['Twelve:', ' Eighty nine:', ' Nine:9.']

re.sub()

re.sub(pattern, replace, string)

The method returns a string where matched occurrences are replaced with the content of replace variable.

If the pattern is not found, re.sub() returns the original string.

In [ ]:
# Program to remove all whitespaces
import re

# multiline string
string = 'abc 12\
de 23 \n f45 6'

# matches all whitespace characters
pattern = '\s+'

# empty string
replace = ''

new_string = re.sub(pattern, replace, string)
print(new_string)

# Output: abc12de23f456

re.subn()

The re.subn() is similar to re.sub() except it returns a tuple of 2 items containing the new string and the number of substitutions made.

In [ ]:
# Program to remove all whitespaces
import re

# multiline string
string = 'abc 12\
de 23 \n f45 6\n'

# matches all whitespace characters
pattern = '\s+'

# empty string
replace = ''

new_string = re.subn(pattern, replace, string)
print(new_string)

# Output: ('abc12de23f456', 4)

('abc12de23f456', 5)

re.search()

match = re.search(pattern, str)

The re.search() method takes two arguments: a pattern and a string. The method looks for the first location where the RegEx pattern produces a match with the string.

If the search is successful, re.search() returns a match object; if not, it returns None.

In [4]:
import re

string = "Python is fun"

# check if 'Python' is at the beginning i.e. \A is a regex anchor that matches only at the beginning of the string (unlike ^, which can match the beginning of each line in multiline mode).
match = re.search('\APython', string)

if match:
  print("pattern found inside the string")
else:
  print("pattern not found")

# Output: pattern found inside the string

pattern found inside the string

In [5]:
#Raw string using r prefix i.e. The r before the string (r'[\n\r]') tells Python:"Treat backslashes (\) as literal characters in the string — don't interpret them as escape characters."

import re

string = '\n and \r are escape sequences.'

result = re.findall(r'[\n\r]', string)
print(result)

# Output: ['\n', '\r']

['\n', '\r']

# Event Driven Programming and GUI (tkinter)

https://www.geeksforgeeks.org/python-gui-tkinter/

https://www.tpointtech.com/python-tkinter

# Introduction to User Input in Python

Python provides multiple ways to take input from users
Common sources of input:

*   Keyboard (via console)
*   Command-line arguments
*   Files
*   Standard input stream (sys.stdin)

https://wiingy.com/learn/python/input-from-console-in-python/

https://www.digitalocean.com/community/tutorials/how-to-receive-user-input-python

https://toph.co/tutorials/5-ways-taking-input-python

**Method 1 - Using input() Function**

Syntax: variable = input("Prompt message")

Returns a string; needs type conversion for numbers

In [ ]:
name = input("Enter your name: ")
print("Hello,", name)

Enter your name: hi
Hello, hi

In [ ]:
age = int(input("Enter your age: "))
print("You will be", age + 1, "years old next year.")

Enter your age: 25
You will be 26 years old next year.

**Method 2 - Reading Multiple Inputs in One Line**

Using split() to take multiple inputs:

In [ ]:
numbers = input("Enter numbers separated by spaces: ").split()
print("Numbers:", numbers)

Enter numbers separated by spaces: 4 5 6
Numbers: ['4', '5', '6']

Converting to integers:

In [ ]:
numbers = list(map(int, input("Enter numbers: ").split()))
print("Sum:", sum(numbers))

Enter numbers: 4 5 6
Sum: 15

#**Important Notes for Google Colab**

Google Colab doesn’t support interactive stdin in the same way as a local terminal.

Instead, use input() for manual input, or upload a file and read it.

**Method 3 - Using sys.stdin.read()**

Reads entire input until EOF (Ctrl+D/Linux, Ctrl+Z/Windows)

Best for large inputs (e.g., JSON, logs)

In [ ]:
import sys
data = sys.stdin.read()
print("You entered:", data)

You entered:

**Method 4 - Using sys.stdin.readline()**

Reads one line at a time

Useful for processing input line-by-line efficiently

In [ ]:
import sys
line = sys.stdin.readline().strip()
print("You entered:", line)

You entered:

**Method 5 - Using fileinput.input()**

Reads from multiple files or standard input

Run with: python script.py file1.txt file2.txt

Useful for batch file processing

In [ ]:
import fileinput
for line in fileinput.input():
    print(line.strip())

In [ ]:
import sys
import fileinput

for line in fileinput.input(files=sys.stdin):
    print("You entered:", line.strip())

**Using Command-Line Arguments (sys.argv)**

Takes input from the command line

Run with: python script.py argument1

In [ ]:
import sys
print("Argument passed:", sys.argv[1])

**Best Practices for Handling Input**

✅ Use input() for simple text input

✅ Use sys.stdin.read() for bulk input processing

✅ Convert input types correctly (int(), float())

✅ Handle exceptions (try-except) for invalid input

✅ Close file handles properly when reading from files

**Comparing Different Input Methods**

![1.png]()